import { 
  Plus,
  Target,
  AlertCircle,
  Edit,
  FileText,
  Calendar,
  Clock,
  UserPlus,
  UserMinus,
  Move,
  MessageSquare,
  Zap,
  Mail,
  Smartphone,
  Languages,
  FileSearch,
  Wand2,
  Smile,
  FolderTree,
  PenTool,
  Search,
  Globe,
  Hash,
  LayoutGrid,
  Shield,
  Gavel,
  Bell,
  Sparkles,
  Users,
  Webhook,
  Bot,
  Server,
  Database,
  Radar,
  ScanSearch,
  GitCompareArrows,
  Microscope,
  Briefcase,
  Paperclip
} from "lucide-react";

export interface AutomationTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  triggerType: string;
  triggerLabel: string;
  actionType: string;
  actionLabel: string;
  icon?: string;
  isAI?: boolean;
  isIntegration?: boolean;
}

export const TRIGGER_TYPES = {
  item_created: { label: "Item Created", icon: Plus, description: "When a new task is created" },
  status_changed: { label: "Status Changed", icon: Target, description: "When task status changes" },
  priority_changed: { label: "Priority Changed", icon: AlertCircle, description: "When task priority changes" },
  column_changed: { label: "Column Changed", icon: Edit, description: "When any column value changes" },
  item_name_changed: { label: "Item Name Changed", icon: FileText, description: "When item name is modified" },
  due_date_approaching: { label: "Due Date Approaching", icon: Calendar, description: "Before due date arrives" },
  due_date_passed: { label: "Due Date Passed", icon: Clock, description: "When due date has passed" },
  assigned: { label: "Person Assigned", icon: UserPlus, description: "When someone is assigned" },
  unassigned: { label: "Person Unassigned", icon: UserMinus, description: "When someone is unassigned" },
  moved_to_group: { label: "Moved to Group", icon: Move, description: "When task moves to different group" },
  file_uploaded: { label: "File Uploaded", icon: FileText, description: "When a file is attached" },
  update_created: { label: "Update Created", icon: MessageSquare, description: "When a comment/update is added" },
  button_clicked: { label: "Button Clicked", icon: Zap, description: "When a button column is clicked" },
  email_received: { label: "Email Received", icon: Mail, description: "When an email is received" },
  approval_status_changed: { label: "Approval Changed", icon: Gavel, description: "When approval status changes" },
  approval_required: { label: "Approval Required", icon: Shield, description: "When item needs approval" },
  deadline_warning: { label: "Deadline Warning", icon: Clock, description: "When a deadline is approaching" },
  compliance_check: { label: "Compliance Check", icon: Shield, description: "When compliance verification is needed" },
  item_tag_added: { label: "Tag Added", icon: Hash, description: "When a tag is added to an item" },
  item_tag_removed: { label: "Tag Removed", icon: Hash, description: "When a tag is removed from an item" },
  item_mentioned_user: { label: "User Mentioned", icon: Users, description: "When a user is @mentioned" },
  file_ocr_completed: { label: "OCR Completed", icon: FileSearch, description: "When OCR/extraction finishes for a file" },
  file_classified: { label: "File Classified", icon: FolderTree, description: "When a file gets a doc_type classification" },
  signal_deadline_detected: { label: "Deadline Detected", icon: Calendar, description: "When OCR text contains a deadline" },
  signal_event_detected: { label: "Event Detected", icon: Calendar, description: "When text suggests an event/meeting/hearing" },
  signal_action_item_detected: { label: "Action Item Detected", icon: Target, description: "When text suggests an action item" },
  signal_privilege_detected: { label: "Privilege Detected", icon: Shield, description: "When content is likely privileged/sensitive" },
  signal_contradiction_detected: { label: "Contradiction Detected", icon: GitCompareArrows, description: "When analysis flags conflicting statements" },
  time_daily_at: { label: "Daily at Time", icon: Clock, description: "Fires daily at a set time" },
  time_before_due_date: { label: "Before Due Date", icon: Clock, description: "Fires X days/hours before due date" },
  time_after_due_date: { label: "After Due Date", icon: Clock, description: "Fires X days/hours after due date if not complete" },
  matter_created: { label: "Matter Created", icon: Briefcase, description: "When a new matter is created" },
  matter_status_changed: { label: "Matter Status Changed", icon: Briefcase, description: "When matter status changes" },
  client_created: { label: "Client Created", icon: Users, description: "When a new client is created" },
  detective_anomaly_threshold: { label: "Anomaly Score Threshold", icon: Radar, description: "When anomaly score exceeds threshold" },
};

export const ACTION_TYPES = {
  change_status: { label: "Change Status", icon: Target, description: "Update the task status" },
  change_priority: { label: "Change Priority", icon: AlertCircle, description: "Update the task priority" },
  move_to_group: { label: "Move to Group", icon: Move, description: "Move task to another group" },
  assign_person: { label: "Assign Person", icon: UserPlus, description: "Assign someone to the task" },
  send_notification: { label: "Send Notification", icon: Bell, description: "Send alert notification" },
  update_field: { label: "Update Field", icon: Edit, description: "Update a specific field" },
  trigger_webhook: { label: "Trigger Webhook", icon: Webhook, description: "Call an external URL" },
  create_item: { label: "Create Item", icon: Plus, description: "Create a new item in a board" },
  ai_fill_column: { label: "Use AI to Fill", icon: Sparkles, description: "Use AI to automatically fill a column" },
  ai_summarize: { label: "Summarize Text", icon: FileSearch, description: "AI-powered text summarization" },
  ai_categorize: { label: "Categorize", icon: FolderTree, description: "AI-powered categorization" },
  ai_detect_language: { label: "Detect Language", icon: Globe, description: "Detect the language of text" },
  ai_translate: { label: "Translate Text", icon: Languages, description: "Translate text to another language" },
  ai_sentiment: { label: "Detect Sentiment", icon: Smile, description: "Analyze text sentiment" },
  ai_improve: { label: "Improve Text", icon: Wand2, description: "AI-powered text improvement" },
  ai_extract: { label: "Extract Info", icon: Search, description: "Extract information from text" },
  ai_write: { label: "Write with AI", icon: PenTool, description: "Generate content with AI" },
  send_slack: { label: "Notify in Channel", icon: MessageSquare, description: "Send Slack notification" },
  send_sms: { label: "Send SMS", icon: Smartphone, description: "Send SMS notification" },
  send_email: { label: "Send Email", icon: Mail, description: "Send email notification" },
  start_time_tracking: { label: "Start Time Tracking", icon: Clock, description: "Start tracking time" },
  stop_time_tracking: { label: "Stop Time Tracking", icon: Clock, description: "Stop tracking time" },
  set_date: { label: "Set Date", icon: Calendar, description: "Set a date field value" },
  request_approval: { label: "Request Approval", icon: Gavel, description: "Route for attorney approval" },
  escalate_review: { label: "Escalate Review", icon: AlertCircle, description: "Escalate to senior reviewer" },
  generate_confirmation: { label: "Generate Confirmation", icon: FileText, description: "Create audit confirmation record" },
  log_compliance: { label: "Log Compliance", icon: Shield, description: "Log compliance verification" },
  create_subtask: { label: "Create Subtask", icon: Plus, description: "Create a related subtask" },
  synseekr_analyze_document: { label: "Analyze Document", icon: Microscope, description: "Deep AI analysis via SynSeekr server" },
  synseekr_extract_entities: { label: "Extract Entities", icon: ScanSearch, description: "Extract people, orgs, dates via SynSeekr" },
  synseekr_rag_query: { label: "RAG Query", icon: Database, description: "Semantic search across case documents" },
  synseekr_run_investigation: { label: "Run Investigation", icon: Radar, description: "Launch full case investigation on SynSeekr" },
  synseekr_detect_contradictions: { label: "Detect Contradictions", icon: GitCompareArrows, description: "Find conflicting statements in case" },
  synseekr_classify_document: { label: "Classify Document", icon: FolderTree, description: "Auto-classify document type via SynSeekr" },
  synseekr_run_agent: { label: "Run AI Agent", icon: Bot, description: "Run specialized legal AI agent" },
  synseekr_search_documents: { label: "Search Documents", icon: Search, description: "Semantic document search via SynSeekr" },
  synseekr_timeline_events: { label: "Get Timeline", icon: Clock, description: "Extract case timeline events" },
  add_tag: { label: "Add Tag", icon: Hash, description: "Add a tag to an item" },
  remove_tag: { label: "Remove Tag", icon: Hash, description: "Remove a tag from an item" },
  add_comment: { label: "Add Comment", icon: MessageSquare, description: "Post a comment/update to an item" },
  link_file: { label: "Link File", icon: Paperclip, description: "Link a file to an item" },
  request_ocr: { label: "Request OCR", icon: FileSearch, description: "Request OCR processing for a file" },
  route_to_folder: { label: "Route to Folder", icon: FolderTree, description: "Route a file to a specific folder" },
  add_file_label: { label: "Add File Label", icon: FileText, description: "Add a label/classification to a file" },
  create_event: { label: "Create Event", icon: Calendar, description: "Create a calendar/hearing event" },
  create_board_column: { label: "Create Column", icon: LayoutGrid, description: "Add a new column to a board" },
};

export const AUTOMATION_CATEGORIES = [
  { id: "legal_workflows", name: "Legal Workflows", color: "bg-gradient-to-r from-amber-500 to-orange-600", icon: Gavel },
  { id: "synseekr", name: "SynSeekr Server", color: "bg-gradient-to-r from-emerald-500 to-teal-600", icon: Server },
  { id: "ai_powered", name: "AI-powered", color: "bg-gradient-to-r from-purple-500 to-pink-500", icon: Sparkles },
  { id: "legal_compliance", name: "Legal Compliance", color: "bg-gradient-to-r from-teal-500 to-emerald-500", icon: Shield },
  { id: "integrations", name: "Integrations", color: "bg-gradient-to-r from-blue-500 to-cyan-500", icon: Globe },
  { id: "status_progress", name: "Status & Progress", color: "bg-purple-500", icon: Target },
  { id: "date_time", name: "Date & Time", color: "bg-yellow-500", icon: Calendar },
  { id: "assignees", name: "Assignees & Ownership", color: "bg-blue-500", icon: Users },
  { id: "notifications", name: "Notifications & Alerts", color: "bg-red-500", icon: Bell },
  { id: "column_updates", name: "Column Updates", color: "bg-gray-500", icon: Edit },
  { id: "cross_board", name: "Cross-Board", color: "bg-orange-500", icon: LayoutGrid },
];

export const AI_AUTOMATION_TEMPLATES: AutomationTemplate[] = [
  {
    id: "ai_fill_item_created",
    name: "When an item is created, use AI to fill in column",
    description: "Automatically populate a column using AI when new items are added",
    category: "ai_powered",
    triggerType: "item_created",
    triggerLabel: "When an item is created",
    actionType: "ai_fill_column",
    actionLabel: "use AI to fill in column",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_fill_update_created",
    name: "When an update is created, use AI to fill in column",
    description: "Use AI to analyze updates and fill column values",
    category: "ai_powered",
    triggerType: "update_created",
    triggerLabel: "When an update is created",
    actionType: "ai_fill_column",
    actionLabel: "use AI to fill in column",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_fill_column_changes",
    name: "When column changes, use AI to fill in column",
    description: "Trigger AI to update columns when values change",
    category: "ai_powered",
    triggerType: "column_changed",
    triggerLabel: "When column changes",
    actionType: "ai_fill_column",
    actionLabel: "use AI to fill in column",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_fill_name_changes",
    name: "When item name changes, use AI to fill in column",
    description: "Update column with AI when item name is modified",
    category: "ai_powered",
    triggerType: "item_name_changed",
    triggerLabel: "When item name changes",
    actionType: "ai_fill_column",
    actionLabel: "use AI to fill in column",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_sentiment_item_created",
    name: "When an item is created, detect sentiment in column and insert into column",
    description: "Analyze sentiment of text content when items are created",
    category: "ai_powered",
    triggerType: "item_created",
    triggerLabel: "When an item is created",
    actionType: "ai_sentiment",
    actionLabel: "detect sentiment",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_sentiment_update",
    name: "When an update is created, detect sentiment in updates and insert into column",
    description: "Analyze sentiment of comments and updates",
    category: "ai_powered",
    triggerType: "update_created",
    triggerLabel: "When an update is created",
    actionType: "ai_sentiment",
    actionLabel: "detect sentiment",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_sentiment_column",
    name: "When column changes, detect sentiment according to these instructions",
    description: "Detect sentiment when column values change",
    category: "ai_powered",
    triggerType: "column_changed",
    triggerLabel: "When column changes",
    actionType: "ai_sentiment",
    actionLabel: "detect sentiment",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_sentiment_name",
    name: "When item name changes, detect sentiment in item name and insert into column",
    description: "Analyze sentiment of item names",
    category: "ai_powered",
    triggerType: "item_name_changed",
    triggerLabel: "When item name changes",
    actionType: "ai_sentiment",
    actionLabel: "detect sentiment",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_write_item_created",
    name: "When an item is created, write with AI in a natural tone, keep it brief, and insert into column",
    description: "Generate content with AI when new items are created",
    category: "ai_powered",
    triggerType: "item_created",
    triggerLabel: "When an item is created",
    actionType: "ai_write",
    actionLabel: "write with AI",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_write_update",
    name: "When an update is created, write with AI in a natural tone, keep it brief, and insert into column",
    description: "Generate AI content based on updates",
    category: "ai_powered",
    triggerType: "update_created",
    triggerLabel: "When an update is created",
    actionType: "ai_write",
    actionLabel: "write with AI",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_write_column",
    name: "When column changes, write with AI in a natural tone, keep it brief, and insert into column",
    description: "Generate content with AI when columns change",
    category: "ai_powered",
    triggerType: "column_changed",
    triggerLabel: "When column changes",
    actionType: "ai_write",
    actionLabel: "write with AI",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_write_name",
    name: "When item name changes, write with AI in a natural tone, keep it brief, and insert into column",
    description: "Generate content with AI when item name changes",
    category: "ai_powered",
    triggerType: "item_name_changed",
    triggerLabel: "When item name changes",
    actionType: "ai_write",
    actionLabel: "write with AI",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_extract_item_created",
    name: "When an item is created, extract info from column according to these instructions, into column",
    description: "Extract specific information from content using AI",
    category: "ai_powered",
    triggerType: "item_created",
    triggerLabel: "When an item is created",
    actionType: "ai_extract",
    actionLabel: "extract info",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_extract_column",
    name: "When column changes, extract info from column according to these instructions, into column",
    description: "Extract information when column values change",
    category: "ai_powered",
    triggerType: "column_changed",
    triggerLabel: "When column changes",
    actionType: "ai_extract",
    actionLabel: "extract info",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_extract_name_item",
    name: "When an item is created, extract info from the item's name based on these instructions, into column",
    description: "Extract information from item names using AI",
    category: "ai_powered",
    triggerType: "item_created",
    triggerLabel: "When an item is created",
    actionType: "ai_extract",
    actionLabel: "extract info from name",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_extract_update",
    name: "When an update is created, extract info from the item's updates based on these instructions, into column",
    description: "Extract information from updates and comments",
    category: "ai_powered",
    triggerType: "update_created",
    triggerLabel: "When an update is created",
    actionType: "ai_extract",
    actionLabel: "extract info",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_extract_name_changes",
    name: "When item name changes, extract info from the item's name according to these instructions, into column",
    description: "Extract information when item names change",
    category: "ai_powered",
    triggerType: "item_name_changed",
    triggerLabel: "When item name changes",
    actionType: "ai_extract",
    actionLabel: "extract info",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_improve_item_created",
    name: "When an item is created, improve text in column, into column. With moderate changes, in a shorter length, and a natural tone.",
    description: "Improve text quality with AI when items are created",
    category: "ai_powered",
    triggerType: "item_created",
    triggerLabel: "When an item is created",
    actionType: "ai_improve",
    actionLabel: "improve text",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_improve_column",
    name: "When column changes, improve text in column, into column. With moderate changes, in a shorter length, and a natural tone.",
    description: "Improve text when column values change",
    category: "ai_powered",
    triggerType: "column_changed",
    triggerLabel: "When column changes",
    actionType: "ai_improve",
    actionLabel: "improve text",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_improve_name",
    name: "When item name changes, improve text in item name, into column. With moderate changes, in a shorter length, and a natural tone.",
    description: "Improve item name text quality",
    category: "ai_powered",
    triggerType: "item_name_changed",
    triggerLabel: "When item name changes",
    actionType: "ai_improve",
    actionLabel: "improve text",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_translate_item_created",
    name: "When an item is created, translate text in column, to Language and insert into column",
    description: "Translate content when items are created",
    category: "ai_powered",
    triggerType: "item_created",
    triggerLabel: "When an item is created",
    actionType: "ai_translate",
    actionLabel: "translate text",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_translate_column",
    name: "When column changes, translate text in column, to Language and insert into column",
    description: "Translate content when column values change",
    category: "ai_powered",
    triggerType: "column_changed",
    triggerLabel: "When column changes",
    actionType: "ai_translate",
    actionLabel: "translate text",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_translate_name",
    name: "When item name changes, translate text in item name, to Language and insert into column",
    description: "Translate item names to another language",
    category: "ai_powered",
    triggerType: "item_name_changed",
    triggerLabel: "When item name changes",
    actionType: "ai_translate",
    actionLabel: "translate text",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_detect_lang_item",
    name: "When an item is created, detect language in column according to these instructions, and insert into column",
    description: "Identify the language of content when items are created",
    category: "ai_powered",
    triggerType: "item_created",
    triggerLabel: "When an item is created",
    actionType: "ai_detect_language",
    actionLabel: "detect language",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_detect_lang_update",
    name: "When an update is created, detect language in updates according to these instructions, and insert into column",
    description: "Identify language of updates and comments",
    category: "ai_powered",
    triggerType: "update_created",
    triggerLabel: "When an update is created",
    actionType: "ai_detect_language",
    actionLabel: "detect language",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_detect_lang_column",
    name: "When column changes, detect language in column according to these instructions, and insert into column",
    description: "Identify language when column values change",
    category: "ai_powered",
    triggerType: "column_changed",
    triggerLabel: "When column changes",
    actionType: "ai_detect_language",
    actionLabel: "detect language",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_detect_lang_name",
    name: "When item name changes, detect language in item name according to these instructions, and insert into column",
    description: "Identify language of item names",
    category: "ai_powered",
    triggerType: "item_name_changed",
    triggerLabel: "When item name changes",
    actionType: "ai_detect_language",
    actionLabel: "detect language",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_categorize_item",
    name: "When an item is created, categorize item name according to these instructions, into column",
    description: "Automatically categorize new items using AI",
    category: "ai_powered",
    triggerType: "item_created",
    triggerLabel: "When an item is created",
    actionType: "ai_categorize",
    actionLabel: "categorize",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_categorize_column",
    name: "When column changes, categorize column according to these instructions, into column",
    description: "Categorize content when column values change",
    category: "ai_powered",
    triggerType: "column_changed",
    triggerLabel: "When column changes",
    actionType: "ai_categorize",
    actionLabel: "categorize",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_categorize_name",
    name: "When item name changes, categorize item name according to these instructions, into column",
    description: "Categorize items when names change",
    category: "ai_powered",
    triggerType: "item_name_changed",
    triggerLabel: "When item name changes",
    actionType: "ai_categorize",
    actionLabel: "categorize",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_categorize_update",
    name: "When an update is created, categorize updates, into column",
    description: "Categorize updates and comments using AI",
    category: "ai_powered",
    triggerType: "update_created",
    triggerLabel: "When an update is created",
    actionType: "ai_categorize",
    actionLabel: "categorize",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_summarize_column",
    name: "When column changes, summarize text in column according to these instructions, into column",
    description: "Create AI summaries when column values change",
    category: "ai_powered",
    triggerType: "column_changed",
    triggerLabel: "When column changes",
    actionType: "ai_summarize",
    actionLabel: "summarize text",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_summarize_item_name",
    name: "When an item is created, summarize text in item name according to these instructions, into column",
    description: "Summarize item names when created",
    category: "ai_powered",
    triggerType: "item_created",
    triggerLabel: "When an item is created",
    actionType: "ai_summarize",
    actionLabel: "summarize text",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_summarize_item_column",
    name: "When an item is created, summarize text in column according to these instructions, into column",
    description: "Summarize column content when items are created",
    category: "ai_powered",
    triggerType: "item_created",
    triggerLabel: "When an item is created",
    actionType: "ai_summarize",
    actionLabel: "summarize text",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_summarize_update",
    name: "When an update is created, summarize text in updates according to these instructions, into column",
    description: "Summarize updates and comments",
    category: "ai_powered",
    triggerType: "update_created",
    triggerLabel: "When an update is created",
    actionType: "ai_summarize",
    actionLabel: "summarize text",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_summarize_name_changes",
    name: "When item name changes, summarize text in column according to these instructions, into column",
    description: "Summarize content when item names change",
    category: "ai_powered",
    triggerType: "item_name_changed",
    triggerLabel: "When item name changes",
    actionType: "ai_summarize",
    actionLabel: "summarize text",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "ai_summarize_button",
    name: "When button clicked, summarize text in column according to these instructions, into column",
    description: "Summarize on button click",
    category: "ai_powered",
    triggerType: "button_clicked",
    triggerLabel: "When button clicked",
    actionType: "ai_summarize",
    actionLabel: "summarize text",
    icon: "sparkles",
    isAI: true,
  },
];

export const INTEGRATION_TEMPLATES: AutomationTemplate[] = [
  {
    id: "slack_notify_channel",
    name: "When ___ changes to ___, notify in channel ___",
    description: "Send Slack notifications when column values change",
    category: "integrations",
    triggerType: "column_changed",
    triggerLabel: "When column changes",
    actionType: "send_slack",
    actionLabel: "notify in channel",
    icon: "slack",
    isIntegration: true,
  },
  {
    id: "slack_priority_high",
    name: "When priority changes to high, notify in channel urgent",
    description: "Alert team in Slack when priority is set to high",
    category: "integrations",
    triggerType: "priority_changed",
    triggerLabel: "When priority changes to high",
    actionType: "send_slack",
    actionLabel: "notify in channel urgent",
    icon: "slack",
    isIntegration: true,
  },
  {
    id: "gmail_create_item",
    name: "When an email is received, create an item in contacts",
    description: "Automatically create items from incoming emails",
    category: "integrations",
    triggerType: "email_received",
    triggerLabel: "When an email is received",
    actionType: "create_item",
    actionLabel: "create an item in contacts",
    icon: "gmail",
    isIntegration: true,
  },
  {
    id: "gmail_create_item_board",
    name: "When an email is received, create an item in _contacts_",
    description: "Create items from emails in a specific board",
    category: "integrations",
    triggerType: "email_received",
    triggerLabel: "When an email is received",
    actionType: "create_item",
    actionLabel: "create an item",
    icon: "gmail",
    isIntegration: true,
  },
  {
    id: "sms_status_change",
    name: "When a status changes to ___, send SMS to ___",
    description: "Send SMS notifications on status changes",
    category: "integrations",
    triggerType: "status_changed",
    triggerLabel: "When a status changes",
    actionType: "send_sms",
    actionLabel: "send SMS",
    icon: "sms",
    isIntegration: true,
  },
  {
    id: "sms_stuck",
    name: "When a status changes to stuck, send SMS to everyone",
    description: "Alert team via SMS when items get stuck",
    category: "integrations",
    triggerType: "status_changed",
    triggerLabel: "When a status changes to stuck",
    actionType: "send_sms",
    actionLabel: "send SMS to everyone",
    icon: "sms",
    isIntegration: true,
  },
];

export const AUTOMATION_TEMPLATES: AutomationTemplate[] = [
  {
    id: "status_create_item",
    name: "When status changes to something, create an item in board",
    description: "Create new items in a board when status changes",
    category: "status_progress",
    triggerType: "status_changed",
    triggerLabel: "When status changes",
    actionType: "create_item",
    actionLabel: "create an item in board",
  },
  {
    id: "status_set_due_date",
    name: "When status changes to something, set due date to current date",
    description: "Set due date when status changes",
    category: "status_progress",
    triggerType: "status_changed",
    triggerLabel: "When status changes",
    actionType: "set_date",
    actionLabel: "set due date",
  },
  {
    id: "status_due_date_plus",
    name: "When status changes to something, set due date to current date plus some days",
    description: "Set due date with offset when status changes",
    category: "status_progress",
    triggerType: "status_changed",
    triggerLabel: "When status changes",
    actionType: "set_date",
    actionLabel: "set due date + days",
  },
  {
    id: "status_connect_boards",
    name: "When status changes to something, create an item in board and connect boards with column",
    description: "Create connected items across boards",
    category: "status_progress",
    triggerType: "status_changed",
    triggerLabel: "When status changes",
    actionType: "create_item",
    actionLabel: "create and connect",
  },
  {
    id: "status_time_tracking",
    name: "When status changes to something, start time tracking. When it changes to something, stop.",
    description: "Control time tracking based on status changes",
    category: "status_progress",
    triggerType: "status_changed",
    triggerLabel: "When status changes",
    actionType: "start_time_tracking",
    actionLabel: "start/stop time tracking",
  },
  {
    id: "move_item_done",
    name: "Move item when status changes",
    description: "When status changes to 'Done', move item to the Completed group",
    category: "status_progress",
    triggerType: "status_changed",
    triggerLabel: "When status changes",
    actionType: "move_to_group",
    actionLabel: "Move to group",
  },
  {
    id: "notify_blocked",
    name: "Notify when item is blocked",
    description: "When status changes to 'Stuck', notify the owner",
    category: "status_progress",
    triggerType: "status_changed",
    triggerLabel: "When status changes",
    actionType: "send_notification",
    actionLabel: "Send notification",
  },
  {
    id: "date_reflect_changes",
    name: "Adjust this date to reflect the changes made in this other date of the same item",
    description: "Sync date columns automatically",
    category: "date_time",
    triggerType: "column_changed",
    triggerLabel: "Adjust this date",
    actionType: "set_date",
    actionLabel: "reflect changes",
  },
  {
    id: "due_date_reminder",
    name: "Due date reminder",
    description: "Send notification 2 days before due date",
    category: "date_time",
    triggerType: "due_date_approaching",
    triggerLabel: "When due date approaches",
    actionType: "send_notification",
    actionLabel: "Send notification",
  },
  {
    id: "overdue_alert",
    name: "Overdue item alert",
    description: "Alert when an item is past its due date",
    category: "date_time",
    triggerType: "due_date_passed",
    triggerLabel: "When due date passes",
    actionType: "send_notification",
    actionLabel: "Send notification",
  },
  {
    id: "cross_board_item_create",
    name: "When an item is created, create an item in board and connect boards with column",
    description: "Create linked items across boards",
    category: "cross_board",
    triggerType: "item_created",
    triggerLabel: "When an item is created",
    actionType: "create_item",
    actionLabel: "create and connect",
  },
  {
    id: "cross_board_another",
    name: "When an item is created in this board, create an item in another board and connect them in the selected board",
    description: "Create mirror items in another board",
    category: "cross_board",
    triggerType: "item_created",
    triggerLabel: "When an item is created",
    actionType: "create_item",
    actionLabel: "create in another board",
  },
  {
    id: "cross_board_column_match",
    name: "When column changes, connect the item where the new value matches this column in another board by this logic",
    description: "Link items based on matching values",
    category: "cross_board",
    triggerType: "column_changed",
    triggerLabel: "When column changes",
    actionType: "update_field",
    actionLabel: "connect matching item",
  },
  {
    id: "assign_on_create",
    name: "Auto-assign on creation",
    description: "When item is created, assign to default owner",
    category: "assignees",
    triggerType: "item_created",
    triggerLabel: "When item is created",
    actionType: "assign_person",
    actionLabel: "Assign person",
  },
  {
    id: "reassign_on_status",
    name: "Reassign on status change",
    description: "When status changes to 'Review', assign to reviewer",
    category: "assignees",
    triggerType: "status_changed",
    triggerLabel: "When status changes",
    actionType: "assign_person",
    actionLabel: "Assign person",
  },
  {
    id: "notify_on_create",
    name: "Notify team on new item",
    description: "When a new item is created, send notification to the team",
    category: "notifications",
    triggerType: "item_created",
    triggerLabel: "When item is created",
    actionType: "send_notification",
    actionLabel: "Send notification",
  },
  {
    id: "notify_on_assign",
    name: "Notify when assigned",
    description: "When someone is assigned, notify them immediately",
    category: "notifications",
    triggerType: "assigned",
    triggerLabel: "When person is assigned",
    actionType: "send_notification",
    actionLabel: "Send notification",
  },
  {
    id: "copy_field_value",
    name: "Copy field value",
    description: "When status changes, copy a value from one field to another",
    category: "column_updates",
    triggerType: "status_changed",
    triggerLabel: "When status changes",
    actionType: "update_field",
    actionLabel: "Update field",
  },
  {
    id: "legal_approval_status_ready",
    name: "When status changes to 'Ready for Review', request approval from senior attorney",
    description: "Route items for legal review when ready",
    category: "legal_compliance",
    triggerType: "status_changed",
    triggerLabel: "When status changes to Ready for Review",
    actionType: "request_approval",
    actionLabel: "request approval",

  },
  {
    id: "legal_approval_document_uploaded",
    name: "When document is uploaded, request attorney approval",
    description: "Require attorney sign-off on new documents",
    category: "legal_compliance",
    triggerType: "file_uploaded",
    triggerLabel: "When document is uploaded",
    actionType: "request_approval",
    actionLabel: "request approval",

  },
  {
    id: "legal_approval_ai_output",
    name: "When AI writes content, request attorney review before sending",
    description: "Require human review of all AI-generated legal content",
    category: "legal_compliance",
    triggerType: "column_changed",
    triggerLabel: "When AI output is generated",
    actionType: "request_approval",
    actionLabel: "request attorney review",

    isAI: true,
  },
  {
    id: "legal_approval_escalate",
    name: "When approval is pending for more than 24 hours, escalate to managing partner",
    description: "Escalate overdue approvals to senior leadership",
    category: "legal_compliance",
    triggerType: "due_date_passed",
    triggerLabel: "When approval is overdue",
    actionType: "escalate_review",
    actionLabel: "escalate to partner",

  },
  {
    id: "legal_approved_generate_confirmation",
    name: "When approved by attorney, generate confirmation record",
    description: "Create audit trail when items are approved",
    category: "legal_compliance",
    triggerType: "approval_status_changed",
    triggerLabel: "When approved",
    actionType: "generate_confirmation",
    actionLabel: "create confirmation",

  },
  {
    id: "legal_deadline_warning",
    name: "When court deadline is approaching, notify attorney and paralegal",
    description: "Alert team about upcoming legal deadlines",
    category: "legal_compliance",
    triggerType: "deadline_warning",
    triggerLabel: "When deadline approaches",
    actionType: "send_notification",
    actionLabel: "notify team",

  },
  {
    id: "legal_compliance_check",
    name: "When matter is marked complete, verify all compliance steps are done",
    description: "Ensure all required steps completed before closing matter",
    category: "legal_compliance",
    triggerType: "status_changed",
    triggerLabel: "When status changes to complete",
    actionType: "log_compliance",
    actionLabel: "verify compliance",

  },
  {
    id: "legal_statute_reminder",
    name: "When statute of limitations date is within 60 days, escalate priority",
    description: "Automatic priority escalation for approaching statute deadlines",
    category: "legal_compliance",
    triggerType: "deadline_warning",
    triggerLabel: "When statute date approaches",
    actionType: "change_priority",
    actionLabel: "escalate priority",

  },
  {
    id: "legal_doc_extract_parties",
    name: "When document is uploaded, AI extract party names, case numbers, and dates",
    description: "Automatically extract key information from legal documents",
    category: "legal_compliance",
    triggerType: "file_uploaded",
    triggerLabel: "When document is uploaded",
    actionType: "ai_extract",
    actionLabel: "extract parties and dates",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "legal_doc_categorize",
    name: "When document is uploaded, AI categorize document type",
    description: "Auto-classify pleadings, motions, discovery, correspondence",
    category: "legal_compliance",
    triggerType: "file_uploaded",
    triggerLabel: "When document is uploaded",
    actionType: "ai_categorize",
    actionLabel: "categorize document",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "legal_doc_summarize",
    name: "When pleading is filed, AI summarize key arguments",
    description: "Generate executive summaries of legal filings",
    category: "legal_compliance",
    triggerType: "file_uploaded",
    triggerLabel: "When pleading is uploaded",
    actionType: "ai_summarize",
    actionLabel: "summarize arguments",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "legal_client_update_status",
    name: "When case milestone is reached, notify client",
    description: "Keep clients informed of major case developments",
    category: "legal_compliance",
    triggerType: "status_changed",
    triggerLabel: "When milestone reached",
    actionType: "send_notification",
    actionLabel: "notify client",

  },
  {
    id: "legal_billing_time_start",
    name: "When status changes to 'Working', start time tracking",
    description: "Auto-start billable time when work begins",
    category: "legal_compliance",
    triggerType: "status_changed",
    triggerLabel: "When status changes to Working",
    actionType: "start_time_tracking",
    actionLabel: "start time",

  },
  {
    id: "legal_billing_time_stop",
    name: "When status changes to 'Complete' or 'Pending', stop time tracking",
    description: "Auto-stop billable time when work pauses",
    category: "legal_compliance",
    triggerType: "status_changed",
    triggerLabel: "When status changes to Complete",
    actionType: "stop_time_tracking",
    actionLabel: "stop time",

  },
  {
    id: "legal_qc_proofread",
    name: "When brief is marked ready, AI improve text for grammar and clarity",
    description: "Auto-proofread legal documents before filing",
    category: "legal_compliance",
    triggerType: "status_changed",
    triggerLabel: "When marked ready for filing",
    actionType: "ai_improve",
    actionLabel: "improve text",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "legal_qc_cite_check",
    name: "When citation column is filled, AI verify citation format",
    description: "Validate legal citation formats",
    category: "legal_compliance",
    triggerType: "column_changed",
    triggerLabel: "When citation added",
    actionType: "ai_extract",
    actionLabel: "verify format",
    icon: "sparkles",
    isAI: true,
  },
];

export const LEGAL_TEMPLATES: AutomationTemplate[] = [
  {
    id: "legal_intake_categorize",
    name: "When new matter is created, AI categorize practice area and assign team",
    description: "Auto-route new matters based on type",
    category: "legal_compliance",
    triggerType: "item_created",
    triggerLabel: "When matter is created",
    actionType: "ai_categorize",
    actionLabel: "categorize and assign",
    icon: "sparkles",
    isAI: true,
  },
  {
    id: "legal_conflict_check",
    name: "When new client added, check for conflicts of interest",
    description: "Automated conflict checking on new matters",
    category: "legal_compliance",
    triggerType: "item_created",
    triggerLabel: "When client is added",
    actionType: "ai_extract",
    actionLabel: "check conflicts",

    isAI: true,
  },
  {
    id: "legal_retainer_reminder",
    name: "When retainer balance is low, notify billing team",
    description: "Monitor retainer balances and alert when low",
    category: "legal_compliance",
    triggerType: "column_changed",
    triggerLabel: "When balance drops below threshold",
    actionType: "send_notification",
    actionLabel: "notify billing",

  },
  {
    id: "legal_privilege_review",
    name: "When document is marked privileged, require attorney confirmation",
    description: "Ensure privilege designations are verified",
    category: "legal_compliance",
    triggerType: "column_changed",
    triggerLabel: "When marked privileged",
    actionType: "request_approval",
    actionLabel: "confirm privilege",

  },
  {
    id: "legal_discovery_deadline",
    name: "When discovery request received, calculate and set response deadline",
    description: "Auto-calculate discovery response deadlines",
    category: "legal_compliance",
    triggerType: "item_created",
    triggerLabel: "When discovery received",
    actionType: "set_date",
    actionLabel: "set deadline",

  },
  {
    id: "legal_motion_response",
    name: "When motion is filed against, calculate opposition deadline",
    description: "Track motion response deadlines automatically",
    category: "legal_compliance",
    triggerType: "item_created",
    triggerLabel: "When motion received",
    actionType: "set_date",
    actionLabel: "set opposition deadline",

  },
  {
    id: "legal_court_hearing_prep",
    name: "When hearing is 7 days away, create preparation checklist",
    description: "Generate hearing prep tasks automatically",
    category: "legal_compliance",
    triggerType: "deadline_warning",
    triggerLabel: "When hearing approaches",
    actionType: "create_subtask",
    actionLabel: "create prep tasks",

  },
  {
    id: "legal_closing_checklist",
    name: "When matter status changes to 'Closing', verify all closing steps",
    description: "Ensure proper matter closing procedures",
    category: "legal_compliance",
    triggerType: "status_changed",
    triggerLabel: "When matter is closing",
    actionType: "log_compliance",
    actionLabel: "verify closing",

  },
];

export const SYNSEEKR_TEMPLATES: AutomationTemplate[] = [
  {
    id: "synseekr_analyze_on_upload",
    name: "When a file is uploaded, analyze document via SynSeekr",
    description: "Run deep AI analysis including classification, summarization, fact extraction, and privilege detection on your local server",
    category: "synseekr",
    triggerType: "file_uploaded",
    triggerLabel: "When a file is uploaded",
    actionType: "synseekr_analyze_document",
    actionLabel: "analyze document via SynSeekr",
    isIntegration: true,
  },
  {
    id: "synseekr_classify_on_upload",
    name: "When a file is uploaded, classify document type via SynSeekr",
    description: "Automatically classify uploaded documents as contracts, pleadings, medical records, etc. using local AI models",
    category: "synseekr",
    triggerType: "file_uploaded",
    triggerLabel: "When a file is uploaded",
    actionType: "synseekr_classify_document",
    actionLabel: "classify document via SynSeekr",
    isIntegration: true,
  },
  {
    id: "synseekr_extract_entities_on_create",
    name: "When an item is created, extract entities via SynSeekr",
    description: "Use GLiNER/GLiREL models to extract people, organizations, locations, dates, and legal terms from case documents",
    category: "synseekr",
    triggerType: "item_created",
    triggerLabel: "When an item is created",
    actionType: "synseekr_extract_entities",
    actionLabel: "extract entities via SynSeekr",
    isIntegration: true,
  },
  {
    id: "synseekr_rag_on_status",
    name: "When status changes, run RAG query via SynSeekr",
    description: "Perform semantic search across case documents using vector embeddings and graph-enhanced retrieval",
    category: "synseekr",
    triggerType: "status_changed",
    triggerLabel: "When status changes",
    actionType: "synseekr_rag_query",
    actionLabel: "run RAG query via SynSeekr",
    isIntegration: true,
  },
  {
    id: "synseekr_investigate_on_status",
    name: "When status changes to 'In Review', run investigation via SynSeekr",
    description: "Launch a full case investigation including claims analysis, evidence review, and credibility scoring",
    category: "synseekr",
    triggerType: "status_changed",
    triggerLabel: "When status changes",
    actionType: "synseekr_run_investigation",
    actionLabel: "run investigation via SynSeekr",
    isIntegration: true,
  },
  {
    id: "synseekr_contradictions_on_upload",
    name: "When a file is uploaded, detect contradictions via SynSeekr",
    description: "Automatically scan for conflicting statements, date mismatches, and timeline inconsistencies across case documents",
    category: "synseekr",
    triggerType: "file_uploaded",
    triggerLabel: "When a file is uploaded",
    actionType: "synseekr_detect_contradictions",
    actionLabel: "detect contradictions via SynSeekr",
    isIntegration: true,
  },
  {
    id: "synseekr_agent_riley_deadline",
    name: "When due date approaches, run Riley deadline agent via SynSeekr",
    description: "Riley tracks court deadlines, filing windows, and statutory limits to ensure compliance",
    category: "synseekr",
    triggerType: "due_date_approaching",
    triggerLabel: "When due date approaches",
    actionType: "synseekr_run_agent",
    actionLabel: "run Riley agent via SynSeekr",
    isIntegration: true,
  },
  {
    id: "synseekr_agent_elena_elements",
    name: "When an item is created, run Elena elements analysis via SynSeekr",
    description: "Elena analyzes legal elements, identifies required proof points, and maps evidence to claims",
    category: "synseekr",
    triggerType: "item_created",
    triggerLabel: "When an item is created",
    actionType: "synseekr_run_agent",
    actionLabel: "run Elena agent via SynSeekr",
    isIntegration: true,
  },
  {
    id: "synseekr_agent_david_weaknesses",
    name: "When status changes, run David weakness analysis via SynSeekr",
    description: "David identifies case weaknesses, potential defenses, and stress-tests legal arguments",
    category: "synseekr",
    triggerType: "status_changed",
    triggerLabel: "When status changes",
    actionType: "synseekr_run_agent",
    actionLabel: "run David agent via SynSeekr",
    isIntegration: true,
  },
  {
    id: "synseekr_search_on_create",
    name: "When an item is created, search related documents via SynSeekr",
    description: "Semantically search across all case documents using vector embeddings and graph relationships",
    category: "synseekr",
    triggerType: "item_created",
    triggerLabel: "When an item is created",
    actionType: "synseekr_search_documents",
    actionLabel: "search documents via SynSeekr",
    isIntegration: true,
  },
  {
    id: "synseekr_timeline_on_upload",
    name: "When a file is uploaded, extract timeline events via SynSeekr",
    description: "Automatically extract dated events and build case timelines from uploaded documents",
    category: "synseekr",
    triggerType: "file_uploaded",
    triggerLabel: "When a file is uploaded",
    actionType: "synseekr_timeline_events",
    actionLabel: "extract timeline via SynSeekr",
    isIntegration: true,
  },
  {
    id: "synseekr_analyze_on_status",
    name: "When status changes to 'Ready for Analysis', analyze all documents via SynSeekr",
    description: "Queue all case documents for comprehensive AI analysis including hot scoring, privilege detection, and fact extraction",
    category: "synseekr",
    triggerType: "status_changed",
    triggerLabel: "When status changes",
    actionType: "synseekr_analyze_document",
    actionLabel: "analyze documents via SynSeekr",
    isIntegration: true,
  },
];

export const LAW_FIRM_WORKFLOW_TEMPLATES: AutomationTemplate[] = [
  {
    id: "lfw_waiting_followup",
    name: "When status changes to 'Waiting on Client', create follow-up task in 3 days",
    description: "Auto-create a follow-up task and comment when item enters Waiting on Client status",
    category: "legal_workflows",
    triggerType: "status_changed",
    triggerLabel: "When status changes to Waiting on Client",
    actionType: "create_item",
    actionLabel: "create follow-up task + comment",
  },
  {
    id: "lfw_intake_assign",
    name: "When new intake item is created, assign intake owner and tag #intake",
    description: "Auto-assign the intake coordinator and tag new intake items for tracking",
    category: "legal_workflows",
    triggerType: "item_created",
    triggerLabel: "When item is created in Intake group",
    actionType: "assign_person",
    actionLabel: "assign intake owner + add tag",
  },
  {
    id: "lfw_due_48h_reminder",
    name: "When due date is within 48 hours and item is not complete, send reminder",
    description: "Notify the assignee and add a comment when deadline is approaching",
    category: "legal_workflows",
    triggerType: "due_date_approaching",
    triggerLabel: "48h before due date + not complete",
    actionType: "send_notification",
    actionLabel: "send reminder + add comment",
  },
  {
    id: "lfw_overdue_urgent",
    name: "When overdue and not complete, move to Urgent group and tag #overdue",
    description: "Escalate overdue items by moving them to the Urgent group with an overdue tag",
    category: "legal_workflows",
    triggerType: "due_date_passed",
    triggerLabel: "After due date + not complete",
    actionType: "move_to_group",
    actionLabel: "move to Urgent + tag #overdue",
  },
  {
    id: "lfw_filed_confirm",
    name: "When status changes to 'Filed', create 'Confirm Filing Receipt' task",
    description: "Auto-create a confirmation task when a document is marked as filed",
    category: "legal_workflows",
    triggerType: "status_changed",
    triggerLabel: "When status changes to Filed",
    actionType: "create_item",
    actionLabel: "create confirmation task",
  },
  {
    id: "lfw_drafting_due",
    name: "When status changes to 'Drafting', set due date 7 days out",
    description: "Auto-set a 7-day drafting deadline when work begins",
    category: "legal_workflows",
    triggerType: "status_changed",
    triggerLabel: "When status changes to Drafting",
    actionType: "set_date",
    actionLabel: "set due date +7 days",
  },
  {
    id: "lfw_urgent_tag_lead",
    name: "When tag #urgent is added, assign lead attorney and move to Urgent",
    description: "Escalate urgent-tagged items to the lead attorney immediately",
    category: "legal_workflows",
    triggerType: "item_tag_added",
    triggerLabel: "When #urgent tag is added",
    actionType: "assign_person",
    actionLabel: "assign lead attorney + move to Urgent",
  },
  {
    id: "lfw_file_ocr",
    name: "When PDF is uploaded to an item, request OCR processing",
    description: "Auto-trigger OCR extraction when PDF files are uploaded",
    category: "legal_workflows",
    triggerType: "file_uploaded",
    triggerLabel: "When PDF is uploaded",
    actionType: "request_ocr",
    actionLabel: "request OCR + add comment",
    isAI: true,
  },
  {
    id: "lfw_ocr_classify",
    name: "When OCR completes, classify document and route to correct folder",
    description: "Auto-classify and file documents after OCR extraction finishes",
    category: "legal_workflows",
    triggerType: "file_ocr_completed",
    triggerLabel: "When OCR completes",
    actionType: "route_to_folder",
    actionLabel: "classify + route to folder",
    isAI: true,
  },
  {
    id: "lfw_deadline_detected",
    name: "When deadline is detected in OCR text, set due date and tag #deadline",
    description: "Auto-capture deadlines found in scanned documents",
    category: "legal_workflows",
    triggerType: "signal_deadline_detected",
    triggerLabel: "When deadline detected in text",
    actionType: "set_date",
    actionLabel: "set due date + tag #deadline",
    isAI: true,
  },
  {
    id: "lfw_event_detected",
    name: "When event/hearing is detected in text, create calendar event",
    description: "Auto-create calendar events from hearings and meetings found in documents",
    category: "legal_workflows",
    triggerType: "signal_event_detected",
    triggerLabel: "When event detected in text",
    actionType: "create_event",
    actionLabel: "create calendar event",
    isAI: true,
  },
  {
    id: "lfw_action_item_detected",
    name: "When action item is detected in text, create task and assign mentioned user",
    description: "Auto-create tasks from action items found in documents and comments",
    category: "legal_workflows",
    triggerType: "signal_action_item_detected",
    triggerLabel: "When action item detected",
    actionType: "create_item",
    actionLabel: "create task + assign user",
    isAI: true,
  },
  {
    id: "lfw_privilege_detected",
    name: "When privilege is detected, tag file as 'privileged' and add comment",
    description: "Auto-flag potentially privileged content for attorney review",
    category: "legal_workflows",
    triggerType: "signal_privilege_detected",
    triggerLabel: "When privilege detected",
    actionType: "add_file_label",
    actionLabel: "label privileged + comment",
    isAI: true,
  },
  {
    id: "lfw_contradiction_review",
    name: "When contradiction is detected, create review task and tag #conflict",
    description: "Flag conflicting statements for lead attorney review",
    category: "legal_workflows",
    triggerType: "signal_contradiction_detected",
    triggerLabel: "When contradiction detected",
    actionType: "create_item",
    actionLabel: "create review task + tag #conflict",
    isAI: true,
  },
  {
    id: "lfw_mentioned_notify",
    name: "When user is @mentioned in a comment, notify them",
    description: "Send in-app notification when a user is mentioned in an update",
    category: "legal_workflows",
    triggerType: "item_mentioned_user",
    triggerLabel: "When user is @mentioned",
    actionType: "send_notification",
    actionLabel: "notify mentioned user",
  },
  {
    id: "lfw_discovery_checklist",
    name: "When status changes to 'Discovery', create checklist subtasks",
    description: "Auto-generate discovery workflow: send requests, calendar deadlines, draft responses",
    category: "legal_workflows",
    triggerType: "status_changed",
    triggerLabel: "When status changes to Discovery",
    actionType: "create_subtask",
    actionLabel: "create discovery checklist",
  },
  {
    id: "lfw_evidence_chain",
    name: "When evidence image is uploaded, create chain-of-custody item",
    description: "Auto-create a chain-of-custody tracking record for uploaded evidence",
    category: "legal_workflows",
    triggerType: "file_uploaded",
    triggerLabel: "When evidence image is uploaded",
    actionType: "create_item",
    actionLabel: "create chain-of-custody record",
  },
  {
    id: "lfw_receipt_expense",
    name: "When receipt is classified, route to Receipts folder and create expense item",
    description: "Auto-file receipts and create expense tracking entries",
    category: "legal_workflows",
    triggerType: "file_classified",
    triggerLabel: "When file classified as receipt",
    actionType: "create_item",
    actionLabel: "route to Receipts + create expense",
  },
  {
    id: "lfw_invoice_billing",
    name: "When invoice is classified, create billing review task",
    description: "Auto-create a billing task when invoice documents are detected",
    category: "legal_workflows",
    triggerType: "file_classified",
    triggerLabel: "When file classified as invoice",
    actionType: "create_item",
    actionLabel: "create billing review task",
  },
  {
    id: "lfw_police_report",
    name: "When police report is classified, add label and create summary task",
    description: "Auto-label police reports and generate a summary task for key facts extraction",
    category: "legal_workflows",
    triggerType: "file_classified",
    triggerLabel: "When file classified as police report",
    actionType: "create_item",
    actionLabel: "label + create summary task",
  },
  {
    id: "lfw_medical_route",
    name: "When medical record is classified, route to Medical folder and tag sensitive",
    description: "Auto-route medical records to the correct folder with sensitivity tagging",
    category: "legal_workflows",
    triggerType: "file_classified",
    triggerLabel: "When file classified as medical record",
    actionType: "route_to_folder",
    actionLabel: "route to Medical + tag sensitive",
  },
  {
    id: "lfw_settlement_tracker",
    name: "When status changes to 'Settlement Negotiation', create offer tracker columns",
    description: "Auto-add Offer Amount and Offer Notes columns for settlement tracking",
    category: "legal_workflows",
    triggerType: "status_changed",
    triggerLabel: "When status changes to Settlement Negotiation",
    actionType: "create_board_column",
    actionLabel: "create Offer Amount + Offer Notes columns",
  },
  {
    id: "lfw_daily_digest",
    name: "Daily digest at 9am: notify team of due and overdue items",
    description: "Send a daily summary of all due today and overdue items to the team",
    category: "legal_workflows",
    triggerType: "time_daily_at",
    triggerLabel: "Daily at 9:00 AM",
    actionType: "send_notification",
    actionLabel: "notify team of due/overdue items",
  },
  {
    id: "lfw_task_complete_status",
    name: "When task is completed, set item status to Complete",
    description: "Auto-update board item status when linked task is finished",
    category: "legal_workflows",
    triggerType: "column_changed",
    triggerLabel: "When task completed",
    actionType: "change_status",
    actionLabel: "set status to Complete",
  },
  {
    id: "lfw_needs_review_assign",
    name: "When status changes to 'Needs Review', assign reviewer",
    description: "Auto-route items to the designated reviewer when ready for review",
    category: "legal_workflows",
    triggerType: "status_changed",
    triggerLabel: "When status changes to Needs Review",
    actionType: "assign_person",
    actionLabel: "assign reviewer",
  },
  {
    id: "lfw_new_client_boards",
    name: "When new client is created, create standard matter boards",
    description: "Auto-generate standard board structure (Intake, Tasks, Evidence, Deadlines) for new clients",
    category: "legal_workflows",
    triggerType: "client_created",
    triggerLabel: "When client is created",
    actionType: "add_comment",
    actionLabel: "create standard boards (proposal)",
  },
  {
    id: "lfw_chat_file_route",
    name: "When file is uploaded to chat, route to board files and link to item",
    description: "Auto-organize files dropped in chat by routing to the correct board folder",
    category: "legal_workflows",
    triggerType: "file_uploaded",
    triggerLabel: "When file uploaded to chat",
    actionType: "route_to_folder",
    actionLabel: "route to board files + link item",
  },
  {
    id: "lfw_due_date_changed_notify",
    name: "When due date is changed, notify the assignee",
    description: "Keep assignees informed when their deadlines are updated",
    category: "legal_workflows",
    triggerType: "due_date_approaching",
    triggerLabel: "When due date is changed",
    actionType: "send_notification",
    actionLabel: "notify assignee of date change",
  },
  {
    id: "lfw_anomaly_investigation",
    name: "When detective anomaly score is high, create investigation task",
    description: "Auto-create an investigation task when the detective board flags an anomaly",
    category: "legal_workflows",
    triggerType: "detective_anomaly_threshold",
    triggerLabel: "When anomaly score exceeds threshold",
    actionType: "create_item",
    actionLabel: "create investigation task + tag #anomaly",
  },
  {
    id: "lfw_overdue_waiting_escalate",
    name: "When overdue and still 'Waiting on Client', escalate to lead attorney",
    description: "Escalate stalled items: tag #escalate, notify lead attorney, add auto-comment",
    category: "legal_workflows",
    triggerType: "time_after_due_date",
    triggerLabel: "After due date + Waiting on Client",
    actionType: "send_notification",
    actionLabel: "tag #escalate + notify lead + comment",
  },
];

export const ALL_TEMPLATES = [...LAW_FIRM_WORKFLOW_TEMPLATES, ...SYNSEEKR_TEMPLATES, ...AI_AUTOMATION_TEMPLATES, ...INTEGRATION_TEMPLATES, ...AUTOMATION_TEMPLATES, ...LEGAL_TEMPLATES];
