import {
  LayoutDashboard,
  Briefcase,
  Users,
  DollarSign,
  FileText,
  FolderOpen,
  FilePlus2,
  Wand2,
  Clock,
  Calendar,
  MessageSquare,
  Gavel,
  Mic,
  ClipboardList,
  ShieldCheck,
  ClipboardCheck,
  Bot,
  Shield,
  Network,
  Zap,
  Home,
  Sparkles,
  Terminal,
  Settings,
  Cpu,
  type LucideIcon,
} from "lucide-react";

export interface FeatureInfo {
  id: string;
  title: string;
  tooltip: string;
  description: string;
  category: "dashboard" | "legal-practice" | "ai-investigation" | "system" | "header";
  route?: string;
  icon?: LucideIcon;
  howToSteps: string[];
  tags: string[];
}

export const FEATURE_METADATA: FeatureInfo[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    tooltip: "Overview of your firm's active cases, deadlines, and key metrics",
    description: "Your command center showing active matters, upcoming deadlines, recent activity, and firm-wide KPIs at a glance.",
    category: "dashboard",
    route: "/",
    icon: Home,
    howToSteps: [
      "Log in to see your personalized dashboard",
      "Review active cases and their current status",
      "Check upcoming deadlines and calendar events",
      "Click any case card to jump directly to that matter",
    ],
    tags: ["overview", "home", "metrics", "cases"],
  },
  {
    id: "vibe-code",
    title: "Vibe Code",
    tooltip: "AI board builder - describe what you need in plain English and get a fully configured board",
    description: "AI-powered board builder that lets you describe a workflow in plain English and automatically generates a customized board with columns, groups, and sample tasks. Includes 18 legal-focused templates.",
    category: "dashboard",
    route: "/vibe-code",
    icon: Sparkles,
    howToSteps: [
      "Click 'Vibe Code' in the sidebar",
      "Type a description of the board you need (e.g., 'deposition scheduling tracker')",
      "Or browse the template gallery and pick a pre-built template",
      "Click 'Generate' and the AI creates your board automatically",
      "Your new board appears in the sidebar under Case Boards",
    ],
    tags: ["ai", "builder", "template", "board", "generate"],
  },
  {
    id: "client-dashboard",
    title: "Client Dashboard",
    tooltip: "View and manage all client relationships, contacts, and engagement history",
    description: "Centralized client relationship management showing all clients, their matters, billing status, and communication history. Drill into individual client profiles for detailed views.",
    category: "legal-practice",
    route: "/client-dashboard",
    icon: LayoutDashboard,
    howToSteps: [
      "Navigate to Client Dashboard from the sidebar",
      "View all clients with their matter counts and billing summaries",
      "Click a client card to see their detailed profile",
      "Use the search bar to find specific clients",
      "Create new clients using the 'Add Client' button",
    ],
    tags: ["clients", "relationships", "contacts", "crm"],
  },
  {
    id: "matters",
    title: "Matters",
    tooltip: "Manage all legal matters - track status, deadlines, parties, and case details",
    description: "Full matter lifecycle management including case creation, status tracking, party management, timeline events, and document linking. Each matter can have its own board, billing, and insights.",
    category: "legal-practice",
    route: "/matters",
    icon: Briefcase,
    howToSteps: [
      "Go to Matters from the sidebar",
      "Click 'New Matter' to create a case",
      "Fill in case details: name, number, practice area, status",
      "Link the matter to a client",
      "Click any matter to see its full detail view with tabs for contacts, timeline, billing, and insights",
    ],
    tags: ["cases", "legal", "management", "lifecycle"],
  },
  {
    id: "clients",
    title: "Clients",
    tooltip: "Client directory - add, edit, and search all firm clients",
    description: "Complete client directory with contact information, company details, and quick access to each client's matters and billing history.",
    category: "legal-practice",
    route: "/clients",
    icon: Users,
    howToSteps: [
      "Open Clients from the sidebar",
      "Browse or search the client list",
      "Click 'Add Client' to create a new client record",
      "Click any client to view their profile and linked matters",
    ],
    tags: ["directory", "contacts", "people"],
  },
  {
    id: "billing",
    title: "Billing",
    tooltip: "Firm-wide billing dashboard - invoices, payments, expenses, and trust accounts",
    description: "Master billing dashboard showing firm-wide financial KPIs, outstanding invoices, recent payments, expense tracking, and IOLTA trust account balances. Drill into client or matter-level billing.",
    category: "legal-practice",
    route: "/billing",
    icon: DollarSign,
    howToSteps: [
      "Navigate to Billing from the sidebar",
      "Review firm-wide financial summary cards",
      "Click 'Invoices' tab to manage all invoices",
      "Click 'Payments' tab to see payment history",
      "Click 'Expenses' tab to track firm expenses",
      "Click 'Trust' tab to manage IOLTA trust transactions",
      "Use filters to narrow by date range, status, or client",
    ],
    tags: ["finance", "invoices", "payments", "money", "trust"],
  },
  {
    id: "documents",
    title: "Documents",
    tooltip: "Filing cabinet - organize, classify, and search all case documents with Bates numbering",
    description: "Two-layer document classification system with controlled vocabulary, metadata tracking, and automatic Bates numbering. Organize documents by category and subcategory for easy retrieval.",
    category: "legal-practice",
    route: "/documents",
    icon: FileText,
    howToSteps: [
      "Go to Documents from the sidebar",
      "Browse documents by category or use search",
      "Upload new documents with the upload button",
      "Assign categories, subcategories, and metadata",
      "Documents automatically receive Bates numbers",
    ],
    tags: ["files", "filing", "bates", "organize", "classify"],
  },
  {
    id: "upload-organizer",
    title: "Upload Organizer",
    tooltip: "Bulk upload and auto-classify documents using AI-powered organization",
    description: "Drag-and-drop bulk file upload with AI-powered automatic classification. Upload multiple documents at once and the system suggests categories, extracts metadata, and organizes them for you.",
    category: "legal-practice",
    route: "/upload-organizer",
    icon: FolderOpen,
    howToSteps: [
      "Open Upload Organizer from the sidebar",
      "Drag files into the upload zone or click to browse",
      "The AI automatically classifies each document",
      "Review and adjust the suggested categories",
      "Click 'Organize' to file them into the system",
    ],
    tags: ["upload", "bulk", "classify", "ai", "organize"],
  },
  {
    id: "document-maker",
    title: "Document Builder",
    tooltip: "AI-powered legal document generator with Utah URCP compliance templates",
    description: "Generate legal documents using AI with 5+ templates including Motion for Continuance, Motion to Dismiss, Civil Complaint, Answer to Complaint, and Subpoena. Features URCP compliance checking and bilingual notice support.",
    category: "legal-practice",
    route: "/document-maker",
    icon: FilePlus2,
    howToSteps: [
      "Navigate to Document Builder",
      "Select a document template (Motion, Complaint, etc.)",
      "Fill in the required case details and parties",
      "Click 'Generate' to have AI draft the document",
      "Review the generated document for accuracy",
      "Use the approval workflow for lawyer sign-off",
      "Export as PDF when finalized",
    ],
    tags: ["generate", "template", "motion", "complaint", "urcp"],
  },
  {
    id: "legal-ai",
    title: "Legal AI",
    tooltip: "AI-powered legal workspace with 14 specialized workflows for research, analysis, and drafting",
    description: "Comprehensive AI legal workspace with three modes: VeriBot (conversational AI with matter context), Library (saved templates), and Draft (generated documents). Features 14 workflow cards including contract analysis, deposition analysis, and jurisdiction comparison.",
    category: "legal-practice",
    route: "/legal-ai",
    icon: Wand2,
    howToSteps: [
      "Open Legal AI from the sidebar",
      "Choose a workflow card (e.g., 'Analyze a Contract')",
      "Upload or paste your document",
      "Select the jurisdiction if applicable",
      "The AI analyzes and provides structured results",
      "Save results to your Library for future reference",
      "Export drafts from the Draft tab",
    ],
    tags: ["research", "analysis", "drafting", "contract", "deposition"],
  },
  {
    id: "time-tracking",
    title: "Time Tracking",
    tooltip: "Track billable hours with timers, manual entries, and UTBMS code assignment",
    description: "Track billable and non-billable time with start/stop timers or manual entries. Assign UTBMS activity codes, link to matters, and export for billing.",
    category: "legal-practice",
    route: "/time-tracking",
    icon: Clock,
    howToSteps: [
      "Go to Time Tracking from the sidebar",
      "Click 'Start Timer' to begin tracking time",
      "Or click 'Manual Entry' to log past time",
      "Select the matter and describe the work performed",
      "Assign a UTBMS activity code",
      "Stop the timer when done - entry is saved automatically",
    ],
    tags: ["hours", "billable", "timer", "utbms"],
  },
  {
    id: "calendar",
    title: "Calendar",
    tooltip: "Firm calendar with deadlines, hearings, depositions, and scheduling",
    description: "Centralized calendar showing all firm events including court dates, filing deadlines, depositions, client meetings, and internal events. Supports multiple views and color-coded categories.",
    category: "legal-practice",
    route: "/calendar",
    icon: Calendar,
    howToSteps: [
      "Open Calendar from the sidebar",
      "View events in month, week, or day view",
      "Click a date to create a new event",
      "Link events to specific matters",
      "Set reminders for important deadlines",
    ],
    tags: ["schedule", "dates", "deadlines", "hearings"],
  },
  {
    id: "communications",
    title: "Communications",
    tooltip: "Client portals, messaging, internal chat, and activity logs in one hub",
    description: "Clio-style communications center with four sections: Client Portals for sharing documents and bills, Text Messages for SMS-style client messaging, Internal Messages for team chat, and Logs for activity tracking.",
    category: "legal-practice",
    route: "/communications",
    icon: MessageSquare,
    howToSteps: [
      "Navigate to Communications",
      "Use Client Portals to share documents with clients",
      "Use Text Messages for client communication",
      "Use Internal Messages for team discussions",
      "Check Logs for a complete activity trail",
    ],
    tags: ["messaging", "chat", "portal", "sms", "logs"],
  },
  {
    id: "master-chat",
    title: "Master Chat",
    tooltip: "Unified team communication channel for firm-wide discussions",
    description: "Central team communication hub for firm-wide announcements, discussions, and collaboration across all practice areas.",
    category: "legal-practice",
    route: "/master-chat",
    icon: MessageSquare,
    howToSteps: [
      "Open Master Chat from the sidebar",
      "Post messages visible to all team members",
      "Use threads to organize topic-specific discussions",
      "Share files and links with the team",
    ],
    tags: ["team", "chat", "collaboration", "internal"],
  },
  {
    id: "approvals",
    title: "Approvals",
    tooltip: "Review and approve pending documents, invoices, and legal filings",
    description: "Centralized approval queue for documents, invoices, and filings that require partner or supervisor sign-off. Includes audit trail for every approval decision.",
    category: "legal-practice",
    route: "/approvals",
    icon: Gavel,
    howToSteps: [
      "Go to Approvals from the sidebar",
      "Review items in the pending approval queue",
      "Click an item to see its full details",
      "Approve, reject, or request changes",
      "All decisions are logged with timestamps",
    ],
    tags: ["review", "sign-off", "approve", "reject", "workflow"],
  },
  {
    id: "meeting-notes",
    title: "Meeting Notes",
    tooltip: "Capture and organize notes from client meetings, depositions, and hearings",
    description: "Structured meeting notes system for capturing key discussion points, action items, and decisions from client meetings, depositions, hearings, and internal conferences.",
    category: "legal-practice",
    route: "/meetings",
    icon: Mic,
    howToSteps: [
      "Navigate to Meeting Notes",
      "Click 'New Meeting' to start a note",
      "Select the meeting type and linked matter",
      "Record key points, decisions, and action items",
      "Action items can be converted to board tasks",
    ],
    tags: ["notes", "meetings", "depositions", "action items"],
  },
  {
    id: "intake-forms",
    title: "Intake Forms",
    tooltip: "Client intake form templates for new client onboarding across practice areas",
    description: "Pre-built intake form templates for 6 practice areas: General, Personal Injury, Family Law, Criminal Defense, Estate Planning, and Employment Law. Features Synergy Law PLLC branding and privacy acknowledgment.",
    category: "legal-practice",
    route: "/intake-forms",
    icon: ClipboardList,
    howToSteps: [
      "Open Intake Forms from the sidebar",
      "Browse available form templates by practice area",
      "Click a template to preview its fields",
      "Share the form link with potential clients",
      "Review submitted responses in the queue",
    ],
    tags: ["onboarding", "new client", "forms", "intake"],
  },
  {
    id: "document-wash",
    title: "Document Wash",
    tooltip: "Sanitize documents by removing metadata, tracked changes, and sensitive hidden content",
    description: "Security tool that sanitizes documents by stripping metadata, tracked changes, comments, hidden text, and embedded objects. Ensures documents are safe before sharing with opposing counsel or courts.",
    category: "legal-practice",
    route: "/document-wash",
    icon: ShieldCheck,
    howToSteps: [
      "Navigate to Document Wash",
      "Upload the document you want to sanitize",
      "Select which metadata types to remove",
      "Click 'Wash' to process the document",
      "Download the cleaned version",
      "Review the wash report for removed items",
    ],
    tags: ["sanitize", "metadata", "security", "clean", "redact"],
  },
  {
    id: "billing-verifier",
    title: "Billing Verifier",
    tooltip: "Verify time entries, detect billing issues, and generate professional invoices",
    description: "Comprehensive time entry verification system with CSV/JSON import, UTBMS code detection, quality checks (vague descriptions, block billing, duplicates), narrative generation, and professional PDF invoice export.",
    category: "legal-practice",
    route: "/billing-verifier",
    icon: ClipboardCheck,
    howToSteps: [
      "Open Billing Verifier from the sidebar",
      "Upload time entries via CSV, JSON, or manual entry",
      "Configure verification settings and thresholds",
      "Review the Results tab for flagged entries",
      "Check Daily tab for per-day aggregation",
      "Make adjustments in the Adjustments tab",
      "Review quality metrics in the Review tab",
      "Export finalized entries as CSV, PDF, or JSON",
    ],
    tags: ["verify", "time entries", "invoice", "utbms", "billing"],
  },
  {
    id: "ai-assistant",
    title: "AI Assistant",
    tooltip: "VeriBot - your AI legal assistant for research, document analysis, and case strategy",
    description: "Multi-model AI assistant (Claude, GPT, Gemini) trained for legal work. Supports matter-specific context injection, document analysis, legal research, case strategy, and automation guidance.",
    category: "ai-investigation",
    route: "/ai-chat",
    icon: Bot,
    howToSteps: [
      "Click AI Assistant or the VeriBot button in the header",
      "Start a new conversation or continue an existing one",
      "Link a matter for case-specific context",
      "Choose your preferred AI model from the dropdown",
      "Type your legal question or paste a document for analysis",
      "The AI responds with matter-aware legal guidance",
    ],
    tags: ["chatbot", "ai", "legal research", "analysis", "veribot"],
  },
  {
    id: "evidence-vault",
    title: "Evidence Vault",
    tooltip: "Tamper-proof evidence storage with SHA-256 chain-of-custody tracking",
    description: "Immutable file storage system with cryptographic SHA-256 hashing for chain-of-custody verification. Every access and modification is logged to maintain evidence integrity for court proceedings.",
    category: "ai-investigation",
    route: "/evidence",
    icon: Shield,
    howToSteps: [
      "Navigate to Evidence Vault",
      "Upload evidence files (documents, images, audio)",
      "Each file is automatically SHA-256 hashed",
      "Link evidence to specific matters",
      "View the chain-of-custody audit trail",
      "Verify file integrity at any time with hash comparison",
    ],
    tags: ["evidence", "chain of custody", "hash", "integrity", "vault"],
  },
  {
    id: "detective-board",
    title: "Detective Board",
    tooltip: "Visual investigation board - map connections between people, events, and evidence",
    description: "Interactive visual investigation board with draggable nodes for people, organizations, events, and evidence. Draw connections to map relationships and uncover patterns in your case.",
    category: "ai-investigation",
    route: "/detective",
    icon: Network,
    howToSteps: [
      "Open Detective Board from the sidebar",
      "Create nodes for people, organizations, or events",
      "Drag nodes to arrange them on the canvas",
      "Draw connections between related nodes",
      "Label connections to describe the relationship",
      "Use the board to identify patterns and build case theories",
    ],
    tags: ["investigation", "visual", "connections", "map", "nodes"],
  },
  {
    id: "automations",
    title: "Automations",
    tooltip: "85+ automation templates - automate repetitive tasks with triggers, conditions, and actions",
    description: "Event-driven automation engine with 85+ pre-built templates including AI-powered actions, legal compliance workflows, and integrations. Use the AI Automation Builder to create custom automations in plain English.",
    category: "ai-investigation",
    route: "/automations",
    icon: Zap,
    howToSteps: [
      "Navigate to Automations",
      "Browse templates by category (AI, Legal, Integration)",
      "Click 'Use Template' to configure an automation",
      "Set the trigger event (e.g., 'When status changes to...')",
      "Define conditions and actions",
      "Or use the AI Builder to describe what you want in plain English",
      "Enable the automation to start running",
    ],
    tags: ["workflow", "triggers", "actions", "automate", "rules"],
  },
  {
    id: "veribot-header",
    title: "VeriBot",
    tooltip: "Quick access to your AI legal assistant - ask questions, analyze documents, get case advice",
    description: "Jump straight to the AI assistant for on-demand legal research, document analysis, and strategic guidance.",
    category: "header",
    route: "/ai-chat",
    icon: Bot,
    howToSteps: [],
    tags: ["ai", "quick access"],
  },
  {
    id: "daily-briefing-header",
    title: "Daily Briefing",
    tooltip: "Your personalized daily summary of tasks, deadlines, and matter updates",
    description: "Start your day with a personalized overview of pending tasks, upcoming deadlines, recent matter activity, and items requiring your attention.",
    category: "header",
    route: "/briefing",
    icon: Calendar,
    howToSteps: [
      "Click Daily Briefing in the header",
      "Review your task summary for today",
      "Check upcoming deadlines this week",
      "See recent activity on your active matters",
      "Click any item to jump to its detail view",
    ],
    tags: ["daily", "summary", "tasks", "briefing"],
  },
  {
    id: "clawbot-header",
    title: "Clawbot",
    tooltip: "Clawbot Gateway - autonomous computer control for shell commands, browser automation, and file management",
    description: "Connect to OpenClaw/Clawbot for autonomous computer control, shell commands, browser automation, and file management through natural language commands.",
    category: "header",
    route: "/clawbot",
    icon: Terminal,
    howToSteps: [
      "Click Clawbot in the header",
      "Type a natural language command",
      "Clawbot executes shell commands, browses the web, or manages files",
      "Review the output and results",
    ],
    tags: ["automation", "shell", "browser", "files"],
  },
  {
    id: "security",
    title: "Security",
    tooltip: "Security dashboard - threat intelligence, scanner traps, and Cloudflare integration status",
    description: "Real-time security monitoring with scanner tripwire traps, IP analytics, threat summaries, and Cloudflare Turnstile integration status. Monitor blocked attacks and suspicious activity.",
    category: "system",
    route: "/security",
    icon: Shield,
    howToSteps: [
      "Navigate to Security from the sidebar footer",
      "Review the threat intelligence summary",
      "Check blocked scanner attempts and flagged IPs",
      "Monitor Cloudflare integration status",
      "Review security event logs",
    ],
    tags: ["threats", "firewall", "cloudflare", "monitoring"],
  },
  {
    id: "settings",
    title: "Settings",
    tooltip: "System settings - user management, roles, integrations, and AI model configuration",
    description: "Configure system settings including user roles (admin/member/viewer), SynSeekr server connection, AI model preferences, and firm-wide defaults.",
    category: "system",
    route: "/settings",
    icon: Settings,
    howToSteps: [
      "Navigate to Settings from the sidebar footer",
      "Manage user roles and permissions",
      "Configure SynSeekr server connection",
      "Set default AI model preferences",
      "Adjust firm-wide settings",
    ],
    tags: ["configuration", "roles", "users", "admin"],
  },
  {
    id: "ai-ops",
    title: "AI Operations Monitor",
    tooltip: "Track AI usage costs, latency, and performance across all models",
    description: "Admin dashboard showing real-time AI operation tracking including token usage, cost estimation, model performance, success rates, and error logs for all AI-powered features.",
    category: "system",
    route: "/settings",
    icon: Cpu,
    howToSteps: [
      "Navigate to Settings and click the AI Ops tab (admin only)",
      "View total AI calls, cost estimates, and average latency",
      "Check usage breakdowns by model and operation type",
      "Review recent errors and their details",
      "Monitor the operations log for individual AI call records",
    ],
    tags: ["ai", "monitoring", "cost", "performance", "admin", "tracking"],
  },
];

export function getFeatureByRoute(route: string): FeatureInfo | undefined {
  return FEATURE_METADATA.find((f) => f.route === route);
}

export function getFeatureById(id: string): FeatureInfo | undefined {
  return FEATURE_METADATA.find((f) => f.id === id);
}

export function searchFeatures(query: string): FeatureInfo[] {
  const q = query.toLowerCase().trim();
  if (!q) return FEATURE_METADATA.filter((f) => f.category !== "header");
  return FEATURE_METADATA.filter(
    (f) =>
      f.category !== "header" &&
      (f.title.toLowerCase().includes(q) ||
        f.description.toLowerCase().includes(q) ||
        f.tags.some((t) => t.includes(q)) ||
        f.tooltip.toLowerCase().includes(q))
  );
}

export const QUICK_START_STEPS = [
  { step: 1, title: "Create a Client", description: "Go to Clients and add your first client with their contact details." },
  { step: 2, title: "Open a Matter", description: "Navigate to Matters and create a new case linked to your client." },
  { step: 3, title: "Set Up a Board", description: "Use Vibe Code to auto-generate a case management board, or create one manually." },
  { step: 4, title: "Upload Documents", description: "Use Upload Organizer to bulk-import case files with AI classification." },
  { step: 5, title: "Track Your Time", description: "Open Time Tracking to start logging billable hours with UTBMS codes." },
  { step: 6, title: "Ask VeriBot", description: "Use the AI Assistant for legal research, document analysis, or case strategy." },
  { step: 7, title: "Generate Documents", description: "Open Document Builder to create motions, complaints, and other filings." },
  { step: 8, title: "Review Billing", description: "Use Billing Verifier to validate time entries and generate invoices." },
];
