export const PRACTICE_AREAS = [
  "Civil Litigation",
  "Criminal Defense",
  "Family Law",
  "Corporate Law",
  "Real Estate",
  "Intellectual Property",
  "Employment Law",
  "Immigration",
  "Personal Injury",
  "Estate Planning",
  "Bankruptcy",
  "Tax Law",
  "Other",
] as const;

export const MATTER_TYPES = [
  "Consultation",
  "Litigation",
  "Transaction",
  "Administrative",
  "Regulatory",
  "Criminal Defense",
  "Civil Litigation",
  "Insurance Litigation",
  "Other",
] as const;

export const UTAH_COURTS = [
  "Third District Court - Salt Lake",
  "Third District Court - West Jordan",
  "Third District Court - Sandy",
  "Third District Court - Tooele",
  "Third District Court - Summit",
  "Second District Court - Ogden",
  "Second District Court - Farmington",
  "Second District Court - Layton",
  "First District Court - Logan",
  "First District Court - Brigham City",
  "Fourth District Court - Provo",
  "Fourth District Court - American Fork",
  "Fourth District Court - Spanish Fork",
  "Fifth District Court - Cedar City",
  "Fifth District Court - St. George",
  "Sixth District Court - Richfield",
  "Sixth District Court - Manti",
  "Seventh District Court - Moab",
  "Seventh District Court - Price",
  "Eighth District Court - Vernal",
  "Utah Supreme Court",
  "Utah Court of Appeals",
  "U.S. District Court - District of Utah",
  "U.S. Bankruptcy Court - District of Utah",
  "U.S. Court of Appeals - 10th Circuit",
  "Utah Justice Court",
  "Utah Juvenile Court",
  "Other",
] as const;

export const UTAH_JUDGES = [
  "Judge Matthew Bates",
  "Judge Jess Betz",
  "Judge Amber Mettler",
  "Judge Robert Faust",
  "Judge Keith Kelly",
  "Judge Laura Scott",
  "Judge Barry Lawrence",
  "Judge Andrew Stone",
  "Judge William Kendall",
  "Judge James Blanch",
  "Judge Adam Mow",
  "Judge Su Chon",
  "Judge Kara Pettit",
  "Judge David Connors",
  "Judge Todd Shaughnessy",
  "Judge Dianna Gibson",
  "Judge Douglas Hogan",
  "Judge Robert Shelby",
  "Judge David Nuffer",
  "Judge Howard Nielson",
  "Judge Tena Campbell",
  "Judge Deno Himonas",
  "Other",
] as const;

export const MATTER_STATUSES = [
  { value: "active", label: "Active" },
  { value: "pending", label: "Pending" },
  { value: "on_hold", label: "On Hold" },
  { value: "closed", label: "Closed" },
  { value: "archived", label: "Archived" },
] as const;

export const STATUS_OPTIONS = [
  { value: "active", label: "Open" },
  { value: "pending", label: "Pending" },
  { value: "on_hold", label: "On Hold" },
  { value: "closed", label: "Closed" },
  { value: "archived", label: "Archived" },
] as const;
