import type { Express } from "express";
import { registerBoardRoutes } from "./boards";
import { registerGroupRoutes } from "./groups";
import { registerTaskRoutes } from "./tasks";
import { registerClientRoutes } from "./clients";
import { registerMatterRoutes } from "./matters";
import { registerEvidenceRoutes } from "./evidence";
import { registerDetectiveRoutes } from "./detective";
import { registerAutomationRoutes } from "./automations";
import { registerAIRoutes } from "./ai";
import { registerFilingRoutes } from "./filing";
import { registerTimeTrackingRoutes } from "./time-tracking";
import { registerCalendarRoutes } from "./calendar";
import { registerApprovalRoutes } from "./approvals";
import { registerBriefingRoutes } from "./briefing";
import { registerClawbotRoutes } from "./clawbot";
import { registerDocumentRoutes } from "./documents";
import { registerSynSeekrRoutes } from "./synseekr";
import { registerMeetingRoutes } from "./meetings";
import { registerVibeCodeRoutes } from "./vibe-code";
import { registerSecurityRoutes } from "./security";
import { registerBillingRoutes } from "./billing";
import { registerInsightsRoutes } from "./insights";
import { registerOrganizerRoutes } from "./organizer";
import { registerChatRoutes } from "./chat";
import { registerWashRoutes } from "./wash";
import { registerBillingVerifierRoutes } from "./billing-verifier";
import { registerAIOpsRoutes } from "./ai-ops";
import { registerTemplateRoutes } from "./templates";
import { registerProcessRecorderRoutes } from "./process-recorder";
import { registerWorkspaceRoutes } from "./workspaces";
import { registerTeamMemberRoutes } from "./team-members";
import { registerDataLinkageRoutes } from "./data-linkage";
import { registerPdfProRoutes } from "./pdf-pro";
import { registerEfilingRoutes } from "./efiling";
import { registerLegalResearchRoutes } from "./legal-research";
import { registerAIPolicyRoutes } from "./ai-policy";
import { registerModelIntelligenceRoutes } from "./model-intelligence";
import { registerLegalVideoRoutes } from "./legal-video";
import { registerPdfForensicsRoutes } from "./pdf-forensics";
import { registerCaseInsightsRoutes } from "./case-insights";
import { registerEmailIntelRoutes } from "./email-intel";
import { registerReportsRoutes } from "./reports";
import { registerSynSeekerInvestigationRoutes } from "./synseeker-investigations";
import { registerAIEventLogRoutes } from "./ai-event-log";
import { registerRolesPermissionsRoutes } from "./roles-permissions";
import { registerRecoveryBinRoutes } from "./recovery-bin";
import { registerCustomFieldRoutes } from "./custom-fields";
import { registerTextSnippetRoutes } from "./text-snippets";
import { registerPIIPolicyRoutes } from "./pii-policy";

export function registerAllRoutes(app: Express): void {
  registerClawbotRoutes(app);
  registerDocumentRoutes(app);
  registerSynSeekrRoutes(app);
  registerOrganizerRoutes(app);
  registerBoardRoutes(app);
  registerGroupRoutes(app);
  registerTaskRoutes(app);
  registerClientRoutes(app);
  registerMatterRoutes(app);
  registerEvidenceRoutes(app);
  registerDetectiveRoutes(app);
  registerAutomationRoutes(app);
  registerAIRoutes(app);
  registerFilingRoutes(app);
  registerTimeTrackingRoutes(app);
  registerCalendarRoutes(app);
  registerApprovalRoutes(app);
  registerBriefingRoutes(app);
  registerMeetingRoutes(app);
  registerVibeCodeRoutes(app);
  registerSecurityRoutes(app);
  registerBillingRoutes(app);
  registerInsightsRoutes(app);
  registerChatRoutes(app);
  registerWashRoutes(app);
  registerBillingVerifierRoutes(app);
  registerTemplateRoutes(app);
  registerProcessRecorderRoutes(app);
  registerWorkspaceRoutes(app);
  registerTeamMemberRoutes(app);
  registerDataLinkageRoutes(app);
  registerAIOpsRoutes(app);
  registerPdfProRoutes(app);
  registerEfilingRoutes(app);
  registerLegalResearchRoutes(app);
  registerAIPolicyRoutes(app);
  registerModelIntelligenceRoutes(app);
  registerLegalVideoRoutes(app);
  registerPdfForensicsRoutes(app);
  registerCaseInsightsRoutes(app);
  registerEmailIntelRoutes(app);
  registerReportsRoutes(app);
  registerSynSeekerInvestigationRoutes(app);
  registerAIEventLogRoutes(app);
  registerRolesPermissionsRoutes(app);
  registerRecoveryBinRoutes(app);
  registerCustomFieldRoutes(app);
  registerTextSnippetRoutes(app);
  registerPIIPolicyRoutes(app);
}
