import { storage } from "./storage";

const demoClients = [
  {
    name: "Estate of Nathan Mercer",
    email: "victoria.mercer@mercerdev.com",
    phone: "(801) 555-0142",
    address: "4892 Shadow Ridge Drive, Provo, UT 84604",
    notes: "Primary case client. Nathan Mercer (deceased) was a prominent Provo Canyon real estate developer found dead at the Canyon Vista Estates construction site on January 8, 2026. Initially ruled accidental death from scaffolding collapse. Wife Victoria Mercer is the estate representative. High-value estate with $5M life insurance policy (double indemnity for accidental death).",
  },
  {
    name: "Victoria Mercer",
    email: "victoria.personal@gmail.com",
    phone: "(801) 555-0198",
    address: "4892 Shadow Ridge Drive, Provo, UT 84604",
    notes: "Widow of Nathan Mercer. Separately represented for personal liability exposure. Had consulted divorce attorney Randall Kemp two weeks before Nathan's death. Stands to inherit $5M life insurance (double indemnity) plus $3.2M in real estate holdings. Alibi: Claims she was at Book Club at neighbor Karen Whitfield's home, 7:30-10PM on night of death. Alibi partially corroborated but has a 45-minute gap (9:15-10:00 PM). No criminal record. Cooperative with investigation.",
  },
  {
    name: "Derek Rawlings",
    email: "derek@rawlings-associates.com",
    phone: "(801) 555-0234",
    address: "1200 East Center Street, Suite 300, Provo, UT 84606",
    notes: "Nathan Mercer's business partner at Canyon Vista Development LLC (50/50 ownership). Facing personal gambling debts of $890,000 to unlicensed gambling operations. Forensic accounting reveals $1.2M in unauthorized transfers from company accounts over 18 months. Had confrontation with Nathan on January 6 witnessed by office staff. Claims he was at home with his wife Rachel on night of death. Rachel Rawlings has not confirmed alibi independently. Subject of separate civil fraud investigation.",
  },
  {
    name: "Tyler Blackwood",
    email: "tyler.blackwood@outlook.com",
    phone: "(385) 555-0167",
    address: "2847 North University Avenue, Apt 4B, Provo, UT 84604",
    notes: "Nathan Mercer's estranged son from first marriage to Diane Blackwood (deceased 2018). Age 28. Returned to Utah from Portland, OR in November 2025 after 6-year estrangement. Recently demanded $500K 'advance inheritance' from Nathan — request denied December 15, 2025. Prior arrests: DUI (2022, Portland), Assault (2020, dismissed). Works part-time at REI in Orem. Phone records show 14 calls to Derek Rawlings in the week before Nathan's death. Initially cooperative, then retained counsel.",
  },
  {
    name: "Jenna Cortez",
    email: "jenna@utahwildlands.org",
    phone: "(801) 555-0276",
    address: "567 West 200 South, Salt Lake City, UT 84101",
    notes: "Executive Director, Utah Wildlands Alliance. Led public campaign against Canyon Vista Estates project, alleging environmental violations in Provo Canyon watershed. Filed formal complaint with Utah DEQ in October 2025. Made public statements: 'Mercer will be stopped by any means necessary' (KSL News interview, Nov 12, 2025). Despite strong motive and public animosity, has solid alibi: was keynote speaker at Sierra Club fundraiser in Park City with 200+ witnesses on night of death. Clean criminal record. Master's in Environmental Science, BYU.",
  },
  {
    name: "Marcus Webb",
    email: "marcus@webbconstruction.com",
    phone: "(801) 555-0189",
    address: "890 South State Street, Orem, UT 84058",
    notes: "General contractor for Canyon Vista Estates project. Licensed contractor (Utah DOPL #378294). Discovered structural deficiencies in Phase 2 foundations and reported them to Nathan in November 2025. Nathan allegedly threatened to 'bury' Webb if he went to inspectors. Webb filed whistleblower complaint with Utah OSHA on December 20, 2025. Was at construction site earlier on January 8 (confirmed by security camera at 3:47 PM) but left at 5:15 PM. Returns to site at 11:30 PM after receiving call about Nathan's body.",
  },
  {
    name: "Officer Brad Hensley",
    email: "bhensley@provopolice.gov",
    phone: "(801) 555-0312",
    address: "Provo City Police Department, 48 South 300 West, Provo, UT 84601",
    notes: "First responding officer to Canyon Vista death scene. Badge #4471. 12-year veteran, Provo PD. Brother-in-law to Derek Rawlings (married to Derek's sister Melissa). Failed to secure the scene properly — allowed Derek Rawlings access to the construction trailer before CSI arrived. Body cam footage has unexplained 8-minute gap (10:47-10:55 PM). Initially classified death as 'industrial accident.' Internal Affairs investigation opened January 25, 2026.",
  },
  {
    name: "Canyon Vista Development LLC",
    email: "admin@canyonvistadev.com",
    phone: "(801) 555-0445",
    address: "1200 East Center Street, Suite 300, Provo, UT 84606",
    notes: "Real estate development company co-owned by Nathan Mercer (50%) and Derek Rawlings (50%). Formed 2019. Primary asset: Canyon Vista Estates, a 45-unit luxury residential development in Provo Canyon valued at $28M upon completion. Currently in Phase 2 construction. Company accounts show $1.2M in unexplained transfers traced to Rawlings. Operating agreement includes key-man life insurance and buy-sell provision triggered by partner death. OSHA investigation pending for structural violations.",
  },
  {
    name: "Mayor Linda Foster",
    email: "linda.foster@provo.gov",
    phone: "(801) 555-0521",
    address: "351 West Center Street, Provo, UT 84601",
    notes: "Mayor of Provo, serving second term. Personally championed the Canyon Vista project through zoning approval despite public opposition. Campaign finance records show $47,500 in donations from Canyon Vista Development LLC and affiliated entities. Text messages recovered from Nathan's phone suggest quid pro quo arrangement for expedited permits. Currently under scrutiny from Utah County Attorney's public integrity unit. Has retained separate counsel. Not a suspect in death but potential co-conspirator in corruption scheme.",
  },
];

const demoMatters = [
  {
    clientIndex: 0,
    name: "State of Utah v. Unknown - Death of Nathan Mercer",
    caseNumber: "2026-CR-00147",
    matterType: "Criminal Defense",
    practiceArea: "criminal",
    status: "active" as const,
    description: "Wrongful death investigation and potential criminal prosecution arising from the death of Nathan Mercer at Canyon Vista Estates construction site on January 8, 2026. Initially classified as accidental death from scaffolding collapse. Medical examiner's supplemental report (January 22) reclassified as 'undetermined manner of death' after discovering blunt force trauma inconsistent with fall mechanics, trace evidence of tampered scaffolding bolts, and toxicology showing 0.14 BAC plus alprazolam. Multiple suspects with motive, means, and opportunity. Fourth Judicial District Court, Utah County.",
    openedDate: "2026-01-10",
    courtName: "Fourth Judicial District Court, Utah County",
    judgeAssigned: "Hon. Robert K. Worthington",
    opposingCounsel: "Utah County Attorney's Office - ADA Patricia Nguyen",
  },
  {
    clientIndex: 1,
    name: "Mercer v. Fidelity National - Life Insurance Claim",
    caseNumber: "2026-CV-00289",
    matterType: "Insurance Litigation",
    practiceArea: "insurance",
    status: "active" as const,
    description: "Action to recover $5M life insurance benefits under Policy #FN-8847291 (double indemnity for accidental death = $10M). Fidelity National has denied the claim pending investigation into manner of death, citing exclusion clauses for death during commission of a crime and suicide. Victoria Mercer is named beneficiary. Policy also has a contestability provision within first 2 years - policy was issued March 2024. Company alleges material misrepresentation on application regarding Nathan's prescription medication use.",
    openedDate: "2026-01-28",
    courtName: "Fourth Judicial District Court, Utah County",
    judgeAssigned: "Hon. Christine Durham",
    opposingCounsel: "Snell & Wilmer LLP - James R. Holbrook",
  },
  {
    clientIndex: 7,
    name: "Canyon Vista Development - OSHA Investigation",
    caseNumber: "OSHA-2026-UT-00034",
    matterType: "Regulatory",
    practiceArea: "regulatory",
    status: "active" as const,
    description: "Utah OSHA investigation into workplace safety violations at Canyon Vista Estates construction site. Triggered by whistleblower complaint (Marcus Webb, December 20, 2025) and subsequent death of Nathan Mercer. Preliminary findings include: substandard scaffolding rated for 500 lbs used for 2,000+ lb loads, missing fall protection equipment, falsified safety inspection reports signed by site foreman Hector Ruiz, and expired equipment certifications. Potential penalties of $156,000+ per willful violation.",
    openedDate: "2026-01-15",
  },
  {
    clientIndex: 2,
    name: "Mercer Estate v. Rawlings - Partnership Dissolution & Fraud",
    caseNumber: "2026-CV-00412",
    matterType: "Civil Litigation",
    practiceArea: "corporate",
    status: "active" as const,
    description: "Civil action for dissolution of Canyon Vista Development LLC partnership and recovery of $1.2M in embezzled funds. Forensic accounting by Eide Bailly LLP reveals Derek Rawlings made 47 unauthorized transfers from operating accounts to personal accounts and shell companies between July 2024 and January 2026. Includes breach of fiduciary duty, conversion, unjust enrichment, and fraudulent concealment claims. Emergency motion for temporary restraining order to freeze Rawlings' assets granted January 30, 2026.",
    openedDate: "2026-01-22",
    courtName: "Fourth Judicial District Court, Utah County",
    judgeAssigned: "Hon. Robert K. Worthington",
    opposingCounsel: "Durham Jones & Pinegar - Steven T. Waterman",
  },
  {
    clientIndex: 8,
    name: "State v. Foster - Public Corruption Investigation",
    caseNumber: "2026-INV-00078",
    matterType: "Criminal Defense",
    practiceArea: "criminal",
    status: "active" as const,
    description: "Representation of Mayor Linda Foster in Utah County Attorney's public integrity investigation. Evidence includes: $47,500 in campaign contributions from Canyon Vista Development LLC, text messages between Foster and Nathan Mercer discussing 'expedited permits' and 'favorable zoning votes,' and testimony from former city planner David Kimball that Foster pressured planning commission to approve Canyon Vista despite environmental objections. Potential charges include bribery of a public official (Utah Code 76-8-105), receiving a bribe (76-8-103), and official misconduct.",
    openedDate: "2026-02-01",
  },
  {
    clientIndex: 3,
    name: "State v. Blackwood - Person of Interest Investigation",
    caseNumber: "2026-CR-00198",
    matterType: "Criminal Defense",
    practiceArea: "criminal",
    status: "active" as const,
    description: "Defense representation for Tyler Blackwood, named as person of interest in Nathan Mercer death investigation. Evidence against: 14 phone calls to Derek Rawlings in week before death, no verifiable alibi for 9PM-midnight on January 8, history of violent behavior (2020 assault charge), financial motive ($500K inheritance demand denied), GPS data placing his phone within 0.3 miles of Canyon Vista site at 9:47 PM on night of death. Evidence in favor: no physical evidence at scene, no DNA/fingerprints on scaffolding, phone records show he was on a 22-minute call with his ex-girlfriend in Portland from 10:05-10:27 PM.",
    openedDate: "2026-01-20",
    courtName: "Fourth Judicial District Court, Utah County",
    judgeAssigned: "Hon. Robert K. Worthington",
    opposingCounsel: "Utah County Attorney's Office - ADA Patricia Nguyen",
  },
  {
    clientIndex: 6,
    name: "Hensley - Internal Affairs Defense",
    caseNumber: "PPD-IA-2026-003",
    matterType: "Administrative",
    practiceArea: "employment",
    status: "active" as const,
    description: "Defense of Officer Brad Hensley in Provo PD Internal Affairs investigation. Allegations: failure to properly secure crime scene, allowing civilian (Derek Rawlings) access to construction trailer, unexplained 8-minute body cam gap, failure to disclose familial relationship to person of interest (Rawlings is brother-in-law), and initial misclassification of death as industrial accident. Hensley claims body cam malfunction was due to cold weather battery issue, and that he didn't know Rawlings was a suspect when allowing access. Polygraph offered but not yet administered.",
    openedDate: "2026-01-26",
  },
];

const demoFiles = [
  {
    matterIndex: 0,
    fileName: "Police_Incident_Report_2026-00147.pdf",
    serverPath: "/matters/2026-CR-00147/reports/Police_Incident_Report.pdf",
    extension: "pdf",
    sizeBytes: 345000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "confidential" as const,
    profile: {
      docCategory: "evidence-records" as const,
      docType: "police-report",
      docRole: "primary" as const,
      captionTitle: "Provo PD Incident Report - Death of Nathan Mercer",
      party: "prosecution" as const,
      filingDate: "2026-01-08",
      docketNumber: "2026-CR-00147",
      version: "final" as const,
      status: "received" as const,
    },
  },
  {
    matterIndex: 0,
    fileName: "Medical_Examiner_Report.pdf",
    serverPath: "/matters/2026-CR-00147/reports/Medical_Examiner_Report.pdf",
    extension: "pdf",
    sizeBytes: 567000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "confidential" as const,
    profile: {
      docCategory: "evidence-records" as const,
      docType: "medical-records",
      docRole: "primary" as const,
      captionTitle: "Utah County Medical Examiner Report - Nathan R. Mercer, Case #ME-2026-0019",
      party: "court" as const,
      filingDate: "2026-01-22",
      version: "final" as const,
      status: "received" as const,
      batesRange: "ME-MERCER-0001 to ME-MERCER-0047",
    },
  },
  {
    matterIndex: 0,
    fileName: "Supplemental_ME_Report_Toxicology.pdf",
    serverPath: "/matters/2026-CR-00147/reports/Supplemental_ME_Report_Toxicology.pdf",
    extension: "pdf",
    sizeBytes: 234000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "confidential" as const,
    profile: {
      docCategory: "evidence-records" as const,
      docType: "medical-records",
      docRole: "exhibit" as const,
      captionTitle: "Supplemental ME Report - Toxicology Results: BAC 0.14, Alprazolam 47ng/mL",
      party: "court" as const,
      filingDate: "2026-01-29",
      version: "final" as const,
      status: "received" as const,
      batesRange: "ME-MERCER-0048 to ME-MERCER-0062",
    },
  },
  {
    matterIndex: 0,
    fileName: "Crime_Scene_Investigation_Report.pdf",
    serverPath: "/matters/2026-CR-00147/reports/CSI_Report.pdf",
    extension: "pdf",
    sizeBytes: 890000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "work-product" as const,
    profile: {
      docCategory: "evidence-records" as const,
      docType: "forensic-report",
      docRole: "primary" as const,
      captionTitle: "CSI Report - Canyon Vista Estates Construction Site, Provo Canyon",
      party: "prosecution" as const,
      filingDate: "2026-01-15",
      version: "final" as const,
      status: "received" as const,
      batesRange: "CSI-CV-0001 to CSI-CV-0134",
    },
  },
  {
    matterIndex: 0,
    fileName: "Scaffolding_Engineering_Analysis.pdf",
    serverPath: "/matters/2026-CR-00147/expert/Scaffolding_Engineering_Analysis.pdf",
    extension: "pdf",
    sizeBytes: 456000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "work-product" as const,
    profile: {
      docCategory: "evidence-records" as const,
      docType: "expert-report",
      docRole: "exhibit" as const,
      captionTitle: "Structural Engineering Analysis - Scaffolding Failure, by Dr. Alan Richter, P.E.",
      party: "plaintiff" as const,
      filingDate: "2026-02-01",
      version: "final" as const,
      status: "final" as const,
      privilegeBasis: "work-product" as const,
    },
  },
  {
    matterIndex: 0,
    fileName: "Witness_Statement_Karen_Whitfield.pdf",
    serverPath: "/matters/2026-CR-00147/witness/Witness_Statement_Whitfield.pdf",
    extension: "pdf",
    sizeBytes: 67000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "confidential" as const,
    profile: {
      docCategory: "evidence-records" as const,
      docType: "witness-statement",
      docRole: "primary" as const,
      captionTitle: "Witness Statement - Karen Whitfield (Victoria Mercer's Alibi Witness)",
      party: "defendant" as const,
      serviceDate: "2026-01-12",
      version: "received" as const,
      status: "received" as const,
    },
  },
  {
    matterIndex: 0,
    fileName: "Witness_Statement_Hector_Ruiz.pdf",
    serverPath: "/matters/2026-CR-00147/witness/Witness_Statement_Ruiz.pdf",
    extension: "pdf",
    sizeBytes: 89000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "confidential" as const,
    profile: {
      docCategory: "evidence-records" as const,
      docType: "witness-statement",
      docRole: "primary" as const,
      captionTitle: "Witness Statement - Hector Ruiz, Site Foreman, Canyon Vista Estates",
      party: "prosecution" as const,
      serviceDate: "2026-01-10",
      version: "received" as const,
      status: "received" as const,
    },
  },
  {
    matterIndex: 0,
    fileName: "Phone_Records_Tyler_Blackwood.pdf",
    serverPath: "/matters/2026-CR-00147/discovery/Phone_Records_Blackwood.pdf",
    extension: "pdf",
    sizeBytes: 234000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "aeo" as const,
    profile: {
      docCategory: "discovery" as const,
      docType: "phone-records",
      docRole: "exhibit" as const,
      captionTitle: "T-Mobile Cell Records - Tyler Blackwood, Dec 1 2025 - Jan 15 2026",
      party: "prosecution" as const,
      serviceDate: "2026-01-18",
      version: "received" as const,
      status: "received" as const,
      batesRange: "CELL-TB-0001 to CELL-TB-0089",
    },
  },
  {
    matterIndex: 0,
    fileName: "Phone_Records_Derek_Rawlings.pdf",
    serverPath: "/matters/2026-CR-00147/discovery/Phone_Records_Rawlings.pdf",
    extension: "pdf",
    sizeBytes: 198000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "aeo" as const,
    profile: {
      docCategory: "discovery" as const,
      docType: "phone-records",
      docRole: "exhibit" as const,
      captionTitle: "Verizon Cell Records - Derek Rawlings, Dec 1 2025 - Jan 15 2026",
      party: "prosecution" as const,
      serviceDate: "2026-01-18",
      version: "received" as const,
      status: "received" as const,
      batesRange: "CELL-DR-0001 to CELL-DR-0067",
    },
  },
  {
    matterIndex: 0,
    fileName: "Mercer_Text_Messages_Foster.pdf",
    serverPath: "/matters/2026-CR-00147/discovery/Mercer_Texts_Foster.pdf",
    extension: "pdf",
    sizeBytes: 145000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "privileged" as const,
    profile: {
      docCategory: "discovery" as const,
      docType: "electronic-communications",
      docRole: "exhibit" as const,
      captionTitle: "Text Messages: Nathan Mercer - Mayor Linda Foster, Sept-Dec 2025",
      party: "prosecution" as const,
      serviceDate: "2026-02-03",
      version: "received" as const,
      status: "received" as const,
      batesRange: "TXT-MF-0001 to TXT-MF-0034",
    },
  },
  {
    matterIndex: 0,
    fileName: "Body_Cam_Footage_Log_Hensley.pdf",
    serverPath: "/matters/2026-CR-00147/evidence/Body_Cam_Log_Hensley.pdf",
    extension: "pdf",
    sizeBytes: 78000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "confidential" as const,
    profile: {
      docCategory: "evidence-records" as const,
      docType: "video-log",
      docRole: "exhibit" as const,
      captionTitle: "Body Camera Footage Log - Officer Hensley, Badge #4471, Jan 8 2026",
      party: "prosecution" as const,
      filingDate: "2026-01-20",
      version: "received" as const,
      status: "received" as const,
    },
  },
  {
    matterIndex: 0,
    fileName: "Security_Camera_Site_Footage.pdf",
    serverPath: "/matters/2026-CR-00147/evidence/Security_Camera_Log.pdf",
    extension: "pdf",
    sizeBytes: 156000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "confidential" as const,
    profile: {
      docCategory: "evidence-records" as const,
      docType: "video-log",
      docRole: "exhibit" as const,
      captionTitle: "Canyon Vista Security Camera Log - Jan 8, 2026, Cameras 1-6",
      party: "prosecution" as const,
      filingDate: "2026-01-12",
      version: "received" as const,
      status: "received" as const,
      batesRange: "SEC-CV-0001 to SEC-CV-0023",
    },
  },
  {
    matterIndex: 1,
    fileName: "Life_Insurance_Policy_FN8847291.pdf",
    serverPath: "/matters/2026-CV-00289/policy/Life_Insurance_Policy.pdf",
    extension: "pdf",
    sizeBytes: 312000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "confidential" as const,
    profile: {
      docCategory: "admin-operations" as const,
      docType: "insurance-policy",
      docRole: "primary" as const,
      captionTitle: "Fidelity National Life Insurance Policy #FN-8847291 - Nathan R. Mercer",
      party: "plaintiff" as const,
      filingDate: "2024-03-15",
      version: "final" as const,
      status: "final" as const,
    },
  },
  {
    matterIndex: 1,
    fileName: "Denial_Letter_Fidelity.pdf",
    serverPath: "/matters/2026-CV-00289/correspondence/Denial_Letter.pdf",
    extension: "pdf",
    sizeBytes: 89000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "confidential" as const,
    profile: {
      docCategory: "correspondence" as const,
      docType: "demand-letter",
      docRole: "primary" as const,
      captionTitle: "Claim Denial Letter - Fidelity National, Re: Policy #FN-8847291",
      party: "defendant" as const,
      serviceDate: "2026-01-25",
      version: "received" as const,
      status: "received" as const,
    },
  },
  {
    matterIndex: 1,
    fileName: "Complaint_Insurance_Bad_Faith.pdf",
    serverPath: "/matters/2026-CV-00289/pleadings/Complaint_Bad_Faith.pdf",
    extension: "pdf",
    sizeBytes: 278000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "confidential" as const,
    profile: {
      docCategory: "pleading" as const,
      docType: "complaint",
      docRole: "primary" as const,
      captionTitle: "Complaint for Insurance Bad Faith and Breach of Contract",
      party: "plaintiff" as const,
      filingDate: "2026-01-28",
      docketNumber: "2026-CV-00289",
      version: "filed" as const,
      status: "filed" as const,
    },
  },
  {
    matterIndex: 2,
    fileName: "OSHA_Whistleblower_Complaint.pdf",
    serverPath: "/matters/OSHA-2026/complaints/Whistleblower_Complaint.pdf",
    extension: "pdf",
    sizeBytes: 167000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "confidential" as const,
    profile: {
      docCategory: "admin-operations" as const,
      docType: "complaint",
      docRole: "primary" as const,
      captionTitle: "OSHA Whistleblower Complaint - Marcus Webb re: Canyon Vista Estates",
      party: "complainant" as const,
      filingDate: "2025-12-20",
      version: "filed" as const,
      status: "filed" as const,
    },
  },
  {
    matterIndex: 2,
    fileName: "OSHA_Inspection_Report.pdf",
    serverPath: "/matters/OSHA-2026/reports/OSHA_Inspection_Report.pdf",
    extension: "pdf",
    sizeBytes: 445000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "confidential" as const,
    profile: {
      docCategory: "evidence-records" as const,
      docType: "inspection-report",
      docRole: "primary" as const,
      captionTitle: "Utah OSHA Inspection Report - Canyon Vista Estates, Inspection #UT-2026-0034",
      party: "agency" as const,
      filingDate: "2026-01-20",
      version: "final" as const,
      status: "received" as const,
      batesRange: "OSHA-CV-0001 to OSHA-CV-0089",
    },
  },
  {
    matterIndex: 3,
    fileName: "Forensic_Accounting_Report_Eide_Bailly.pdf",
    serverPath: "/matters/2026-CV-00412/expert/Forensic_Accounting_Report.pdf",
    extension: "pdf",
    sizeBytes: 1234000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "work-product" as const,
    profile: {
      docCategory: "evidence-records" as const,
      docType: "expert-report",
      docRole: "primary" as const,
      captionTitle: "Forensic Accounting Report - Canyon Vista Development LLC, by Eide Bailly LLP",
      party: "plaintiff" as const,
      filingDate: "2026-01-20",
      version: "final" as const,
      status: "final" as const,
      privilegeBasis: "work-product" as const,
      batesRange: "ACCT-CV-0001 to ACCT-CV-0234",
    },
  },
  {
    matterIndex: 3,
    fileName: "TRO_Motion_Asset_Freeze.pdf",
    serverPath: "/matters/2026-CV-00412/motions/TRO_Motion.pdf",
    extension: "pdf",
    sizeBytes: 198000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "confidential" as const,
    profile: {
      docCategory: "motion" as const,
      docType: "motion-tro",
      docRole: "primary" as const,
      captionTitle: "Emergency Motion for Temporary Restraining Order - Asset Freeze",
      party: "plaintiff" as const,
      filingDate: "2026-01-28",
      hearingDate: "2026-01-30",
      docketNumber: "2026-CV-00412",
      version: "filed" as const,
      status: "filed" as const,
    },
  },
  {
    matterIndex: 3,
    fileName: "TRO_Order_Granted.pdf",
    serverPath: "/matters/2026-CV-00412/orders/TRO_Order.pdf",
    extension: "pdf",
    sizeBytes: 89000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "confidential" as const,
    profile: {
      docCategory: "order-ruling" as const,
      docType: "court-order",
      docRole: "primary" as const,
      captionTitle: "Order Granting Temporary Restraining Order - Rawlings Asset Freeze",
      party: "court" as const,
      filingDate: "2026-01-30",
      docketNumber: "2026-CV-00412",
      version: "final" as const,
      status: "final" as const,
    },
  },
  {
    matterIndex: 3,
    fileName: "Operating_Agreement_Canyon_Vista.pdf",
    serverPath: "/matters/2026-CV-00412/corporate/Operating_Agreement.pdf",
    extension: "pdf",
    sizeBytes: 345000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "confidential" as const,
    profile: {
      docCategory: "admin-operations" as const,
      docType: "operating-agreement",
      docRole: "primary" as const,
      captionTitle: "Operating Agreement - Canyon Vista Development LLC (2019, Amended 2023)",
      party: "client" as const,
      filingDate: "2019-06-15",
      version: "final" as const,
      status: "final" as const,
    },
  },
  {
    matterIndex: 4,
    fileName: "Campaign_Finance_Records_Foster.pdf",
    serverPath: "/matters/2026-INV-00078/discovery/Campaign_Finance_Records.pdf",
    extension: "pdf",
    sizeBytes: 234000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "privileged" as const,
    profile: {
      docCategory: "evidence-records" as const,
      docType: "financial-records",
      docRole: "exhibit" as const,
      captionTitle: "Campaign Finance Disclosure - Linda Foster, 2023-2025 Election Cycles",
      party: "prosecution" as const,
      serviceDate: "2026-02-03",
      version: "received" as const,
      status: "received" as const,
      batesRange: "CF-FOSTER-0001 to CF-FOSTER-0056",
    },
  },
  {
    matterIndex: 5,
    fileName: "GPS_Data_Analysis_Blackwood.pdf",
    serverPath: "/matters/2026-CR-00198/evidence/GPS_Data_Analysis.pdf",
    extension: "pdf",
    sizeBytes: 178000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "confidential" as const,
    profile: {
      docCategory: "evidence-records" as const,
      docType: "forensic-report",
      docRole: "exhibit" as const,
      captionTitle: "GPS Location Analysis - Tyler Blackwood Phone, Jan 8-9 2026",
      party: "prosecution" as const,
      serviceDate: "2026-01-25",
      version: "received" as const,
      status: "received" as const,
    },
  },
  {
    matterIndex: 6,
    fileName: "Internal_Affairs_Complaint.pdf",
    serverPath: "/matters/PPD-IA-2026-003/complaints/IA_Complaint.pdf",
    extension: "pdf",
    sizeBytes: 123000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "confidential" as const,
    profile: {
      docCategory: "admin-operations" as const,
      docType: "complaint",
      docRole: "primary" as const,
      captionTitle: "Internal Affairs Complaint - Officer Brad Hensley, Badge #4471",
      party: "agency" as const,
      filingDate: "2026-01-25",
      version: "filed" as const,
      status: "filed" as const,
    },
  },
  {
    matterIndex: 6,
    fileName: "Body_Cam_Gap_Analysis.pdf",
    serverPath: "/matters/PPD-IA-2026-003/evidence/Body_Cam_Analysis.pdf",
    extension: "pdf",
    sizeBytes: 234000,
    isEmail: false,
    isAttachment: false,
    confidentiality: "work-product" as const,
    profile: {
      docCategory: "evidence-records" as const,
      docType: "forensic-report",
      docRole: "exhibit" as const,
      captionTitle: "Digital Forensics Analysis - Body Camera Gap, 10:47-10:55 PM, Jan 8 2026",
      party: "prosecution" as const,
      filingDate: "2026-02-01",
      version: "received" as const,
      status: "received" as const,
    },
  },
];

const demoEvidence = [
  {
    matterIndex: 0,
    originalName: "Security_Camera_Footage_Cam3.mp4",
    originalUrl: "https://evidence.vericase.local/mercer/security-cam3.mp4",
    originalHash: "sha256:a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2",
    originalSize: 289000000,
    originalMimeType: "video/mp4",
    evidenceType: "video" as const,
    confidentiality: "confidential" as const,
    description: "Canyon Vista Security Camera 3 (north entrance) - Jan 8, 2026, 5PM-midnight. Shows Marcus Webb departing at 5:15 PM, Nathan Mercer arriving at 7:22 PM alone, an unidentified dark SUV entering at 8:45 PM (plates obscured by mud), and the SUV departing at 9:38 PM. Critical: The scaffolding area is partially visible, and a figure is seen near the scaffolding at 9:12 PM but resolution is too low for identification.",
    tags: ["security-footage", "critical", "timeline", "canyon-vista"],
    uploadedBy: "Det. Ryan Kimura, Provo PD",
  },
  {
    matterIndex: 0,
    originalName: "Scaffolding_Bolt_Photos.zip",
    originalUrl: "https://evidence.vericase.local/mercer/scaffolding-bolts.zip",
    originalHash: "sha256:b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3",
    originalSize: 45600000,
    originalMimeType: "application/zip",
    evidenceType: "document" as const,
    confidentiality: "confidential" as const,
    description: "High-resolution photographs of scaffolding bolts recovered from collapse site. Photos taken by CSI unit on January 9, 2026. Key finding: 4 of 6 load-bearing bolts show tool marks consistent with deliberate loosening using a 15mm socket wrench. Thread damage pattern indicates bolts were backed out approximately 3/4 turn - enough to appear secure on visual inspection but fail under dynamic load. Dr. Alan Richter (structural engineer) confirms this is inconsistent with vibration loosening or manufacturing defect.",
    tags: ["physical-evidence", "forensic", "scaffolding", "critical"],
    uploadedBy: "CSI Unit, Provo PD",
  },
  {
    matterIndex: 0,
    originalName: "Nathan_Mercer_Phone_Extraction.pdf",
    originalUrl: "https://evidence.vericase.local/mercer/phone-extraction.pdf",
    originalHash: "sha256:c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4",
    originalSize: 5670000,
    originalMimeType: "application/pdf",
    evidenceType: "document" as const,
    confidentiality: "aeo" as const,
    description: "Cellebrite extraction of Nathan Mercer's iPhone 15 Pro recovered from the scene. Contains text messages, call logs, GPS data, photos, and deleted data recovery. Key findings: (1) Last text to Victoria at 7:18 PM - 'Working late at site. Don't wait up.' (2) Deleted texts to unknown burner number discussing '$2M cash position' and 'Cayman account ready' (3) Internet searches on Jan 3-5 for 'fake death insurance fraud' and 'countries without US extradition' (4) Draft email to offshore attorney in Belize never sent.",
    tags: ["digital-forensics", "phone", "critical", "twist"],
    uploadedBy: "Digital Forensics Lab, Utah DPS",
  },
  {
    matterIndex: 0,
    originalName: "Hensley_Body_Cam_Full.mp4",
    originalUrl: "https://evidence.vericase.local/mercer/hensley-bodycam.mp4",
    originalHash: "sha256:d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5",
    originalSize: 123400000,
    originalMimeType: "video/mp4",
    evidenceType: "video" as const,
    confidentiality: "confidential" as const,
    description: "Officer Hensley body camera footage from January 8, 2026 response. Begins at 10:32 PM upon arrival at Canyon Vista. Shows Hensley approaching construction site, finding Nathan Mercer's body beneath collapsed scaffolding at Building 7. Gap from 10:47-10:55 PM (8 minutes). When footage resumes, Derek Rawlings is visible inside the construction trailer, and Hensley is speaking to him. Rawlings appears agitated and is holding what appears to be a manila folder. Digital forensics cannot determine if gap was manual shutoff or malfunction.",
    tags: ["body-cam", "critical", "gap", "hensley", "rawlings"],
    uploadedBy: "Provo PD Records Division",
  },
  {
    matterIndex: 0,
    originalName: "Fingerprint_Analysis_Report.pdf",
    originalUrl: "https://evidence.vericase.local/mercer/fingerprints.pdf",
    originalHash: "sha256:e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6",
    originalSize: 2340000,
    originalMimeType: "application/pdf",
    evidenceType: "document" as const,
    confidentiality: "confidential" as const,
    description: "Utah DPS Crime Lab fingerprint analysis from scaffolding bolts and surrounding area. Results: Nathan Mercer's prints on scaffolding rails (expected). Marcus Webb's prints on scaffolding frame (expected - he works on site). Derek Rawlings' prints found on construction trailer door and desk (he claims he hadn't visited site in 2 weeks). One unidentified partial print on scaffolding bolt #3 - not matching any known suspect. No prints from Tyler Blackwood found at scene.",
    tags: ["fingerprints", "forensic", "crime-lab"],
    uploadedBy: "Utah DPS Crime Lab",
  },
  {
    matterIndex: 0,
    originalName: "Rawlings_Bank_Records.pdf",
    originalUrl: "https://evidence.vericase.local/mercer/rawlings-bank.pdf",
    originalHash: "sha256:f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7",
    originalSize: 3450000,
    originalMimeType: "application/pdf",
    evidenceType: "document" as const,
    confidentiality: "aeo" as const,
    description: "Subpoenaed bank records from Zions Bank, Chase, and two Cayman Islands accounts linked to Derek Rawlings. Shows pattern of transfers from Canyon Vista operating account to personal accounts and shell companies (Rawlings Holdings LLC, Mountain Peak Ventures). Total identified: $1,247,832 over 18 months. Also shows $890,000 in payments to 'Desert Sun Enterprises' - traced to unlicensed gambling operation in West Valley City. Buy-sell agreement would give Rawlings sole control of Canyon Vista upon Nathan's death.",
    tags: ["financial-records", "embezzlement", "gambling", "motive"],
    uploadedBy: "Eide Bailly LLP, Forensic Accounting",
  },
  {
    matterIndex: 5,
    originalName: "Blackwood_Portland_Assault_Record.pdf",
    originalUrl: "https://evidence.vericase.local/blackwood/portland-record.pdf",
    originalHash: "sha256:a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8",
    originalSize: 456000,
    originalMimeType: "application/pdf",
    evidenceType: "document" as const,
    confidentiality: "confidential" as const,
    description: "Multnomah County (Portland, OR) records for Tyler Blackwood. 2020 assault charge - bar fight, victim suffered broken jaw. Charge dismissed after victim declined to cooperate. 2022 DUI - BAC 0.19, license suspended 90 days. Character evidence showing propensity for violence and substance abuse. However, Portland PD notes indicate Blackwood completed anger management program in 2023.",
    tags: ["criminal-history", "character-evidence", "blackwood"],
    uploadedBy: "Multnomah County Records",
  },
];

const demoDetectiveNodes = [
  {
    matterIndex: 0,
    nodes: [
      { type: "person" as const, title: "Nathan Mercer (Deceased)", description: "Age 54. Prominent Provo Canyon developer. Found dead beneath collapsed scaffolding at Canyon Vista Estates, Building 7, at approximately 10:30 PM on January 8, 2026. BAC 0.14, alprazolam in system. ME found blunt force trauma inconsistent with simple fall. Deleted phone searches suggest he may have been planning to fake his own death and flee to Belize with $2M in hidden cash.", position: { x: 400, y: 50 }, color: "#ef4444" },
      { type: "person" as const, title: "Victoria Mercer", description: "Age 48. Wife of Nathan. Beneficiary of $5M life insurance (double indemnity = $10M). Consulted divorce attorney Randall Kemp on Dec 26, 2025. Claims she was at book club 7:30-10PM. Alibi has 45-minute gap (9:15-10PM). Neighbor Karen Whitfield confirms she arrived at 7:30 but says Victoria left 'around 9:15 to take a phone call in her car' and returned 'maybe 20 minutes later.' No known means to tamper with scaffolding.", position: { x: 100, y: 200 }, color: "#f59e0b" },
      { type: "person" as const, title: "Derek Rawlings", description: "Age 51. Business partner, 50% owner Canyon Vista LLC. Embezzled $1.2M from company. $890K gambling debts. Buy-sell agreement gives him sole control if Nathan dies. Confronted Nathan on Jan 6. Claims home alibi (wife hasn't confirmed). Fingerprints found in construction trailer despite claiming he hadn't visited in 2 weeks. Brother-in-law to responding Officer Hensley. 14 calls with Tyler Blackwood in week before death.", position: { x: 700, y: 200 }, color: "#dc2626" },
      { type: "person" as const, title: "Tyler Blackwood", description: "Age 28. Nathan's estranged son. Returned to Utah Nov 2025 after 6-year absence. Demanded $500K inheritance advance - denied Dec 15. Prior assault and DUI charges. GPS places phone 0.3 miles from Canyon Vista at 9:47 PM night of death. 14 calls to Rawlings pre-death. BUT: On phone with ex-girlfriend 10:05-10:27 PM, no DNA/prints at scene.", position: { x: 400, y: 350 }, color: "#7c3aed" },
      { type: "person" as const, title: "Jenna Cortez", description: "Age 35. Director, Utah Wildlands Alliance. Led campaign against Canyon Vista project. Publicly stated 'Mercer will be stopped by any means necessary.' BUT: Ironclad alibi - keynote speaker at Sierra Club fundraiser in Park City with 200+ witnesses night of death. Clean record. Strong motive but no opportunity.", position: { x: 100, y: 500 }, color: "#10b981" },
      { type: "person" as const, title: "Marcus Webb", description: "Age 44. General contractor. Filed OSHA whistleblower complaint Dec 20, 2025. Nathan threatened to 'bury' him. On site until 5:15 PM day of death (confirmed by camera). Returns at 11:30 PM after body found. Had knowledge of scaffolding weak points. Currently cooperating with investigation.", position: { x: 700, y: 500 }, color: "#3b82f6" },
      { type: "person" as const, title: "Officer Brad Hensley", description: "Age 38. First responder. Brother-in-law to Rawlings. 8-minute body cam gap. Let Rawlings into trailer before CSI. Classified death as accident. Now under IA investigation. Possible cover-up or evidence tampering.", position: { x: 400, y: 650 }, color: "#f97316" },
      { type: "person" as const, title: "Mayor Linda Foster", description: "Age 56. Championed Canyon Vista project. $47.5K in campaign donations from Canyon Vista LLC. Text messages with Nathan suggest quid pro quo for permits. Under public integrity investigation. May have known about Nathan's fraud schemes.", position: { x: 100, y: 650 }, color: "#ec4899" },
      { type: "location" as const, title: "Canyon Vista Estates - Building 7", description: "Construction site in Provo Canyon. Location of death. Scaffolding at 3rd floor level, approximately 35 feet. 4 of 6 load-bearing bolts deliberately loosened with 15mm socket wrench. Security cameras show unidentified dark SUV 8:45-9:38 PM. Area not well lit after 6 PM.", position: { x: 400, y: 200 }, color: "#ef4444" },
      { type: "evidence" as const, title: "Tampered Scaffolding Bolts", description: "4 of 6 load-bearing bolts backed out 3/4 turn with 15mm socket wrench. Tool marks confirm deliberate loosening. Would appear secure on visual inspection but fail under dynamic load. This was not an accident.", position: { x: 650, y: 50 }, color: "#dc2626" },
      { type: "evidence" as const, title: "Nathan's Deleted Phone Data", description: "Searches for 'fake death insurance fraud,' 'countries without US extradition,' draft email to Belize attorney, texts about '$2M cash position' and 'Cayman account.' Was Nathan planning to fake his own death? Did someone discover his plan and use it against him?", position: { x: 150, y: 50 }, color: "#f59e0b" },
      { type: "evidence" as const, title: "Unidentified Dark SUV", description: "Entered Canyon Vista at 8:45 PM, departed 9:38 PM. License plates obscured by mud (deliberate?). Make/model analysis pending - appears to be 2022-2024 Chevrolet Tahoe, dark gray or black. Derek Rawlings drives a 2023 black Chevrolet Tahoe.", position: { x: 700, y: 350 }, color: "#8b5cf6" },
      { type: "event" as const, title: "Rawlings-Mercer Confrontation", description: "January 6, 2026 at Canyon Vista offices. Witnessed by office manager Diane Walsh and intern Kevin Torres. Rawlings and Nathan argued loudly for 20+ minutes. Nathan accused Rawlings of 'stealing from the company.' Rawlings reportedly said 'You'll regret this.' Walsh called it 'the worst she'd ever seen between them.'", position: { x: 550, y: 500 }, color: "#ef4444" },
      { type: "event" as const, title: "Body Cam Gap - 10:47-10:55 PM", description: "8-minute unexplained gap in Officer Hensley's body camera footage. When footage resumes, Rawlings is inside construction trailer holding a manila folder. Hensley claims cold weather battery malfunction. Digital forensics lab says gap could be manual shutoff OR battery issue - inconclusive.", position: { x: 250, y: 650 }, color: "#f97316" },
      { type: "evidence" as const, title: "Unidentified Fingerprint on Bolt #3", description: "Partial fingerprint found on scaffolding bolt #3 (one of the tampered bolts). Does not match any known suspect: not Mercer, Rawlings, Blackwood, Webb, Hensley, or any construction worker on file. Submitted to AFIS - no match returned. Whose print is this?", position: { x: 550, y: 650 }, color: "#dc2626" },
    ],
    connections: [
      { sourceIndex: 0, targetIndex: 8, label: "Found dead at location", connectionType: "related" as const },
      { sourceIndex: 0, targetIndex: 10, label: "Planning escape?", connectionType: "contradicts" as const },
      { sourceIndex: 0, targetIndex: 9, label: "Killed by tampered bolts", connectionType: "supports" as const },
      { sourceIndex: 1, targetIndex: 0, label: "Wife - $10M beneficiary", connectionType: "related" as const },
      { sourceIndex: 2, targetIndex: 0, label: "Partner - $1.2M embezzled", connectionType: "supports" as const },
      { sourceIndex: 2, targetIndex: 3, label: "14 calls before death", connectionType: "supports" as const },
      { sourceIndex: 2, targetIndex: 11, label: "Drives matching SUV", connectionType: "supports" as const },
      { sourceIndex: 2, targetIndex: 12, label: "Argument 2 days before", connectionType: "timeline" as const },
      { sourceIndex: 2, targetIndex: 6, label: "Brother-in-law", connectionType: "related" as const },
      { sourceIndex: 3, targetIndex: 0, label: "Estranged son, denied $500K", connectionType: "supports" as const },
      { sourceIndex: 3, targetIndex: 2, label: "Conspiring together?", connectionType: "supports" as const },
      { sourceIndex: 4, targetIndex: 0, label: "Public threats but solid alibi", connectionType: "contradicts" as const },
      { sourceIndex: 5, targetIndex: 0, label: "Whistleblower, threatened", connectionType: "related" as const },
      { sourceIndex: 5, targetIndex: 9, label: "Knew scaffolding weak points", connectionType: "supports" as const },
      { sourceIndex: 6, targetIndex: 13, label: "Unexplained footage gap", connectionType: "supports" as const },
      { sourceIndex: 6, targetIndex: 2, label: "Let Rawlings access trailer", connectionType: "supports" as const },
      { sourceIndex: 7, targetIndex: 0, label: "Corrupt permits deal", connectionType: "related" as const },
      { sourceIndex: 11, targetIndex: 8, label: "At scene 8:45-9:38 PM", connectionType: "timeline" as const },
      { sourceIndex: 14, targetIndex: 9, label: "Unknown person touched bolt", connectionType: "contradicts" as const },
    ],
  },
];

const demoMeetings = [
  {
    title: "Mercer Case - Initial Strategy Session",
    date: "2026-01-12T09:00:00.000Z",
    duration: 78,
    status: "summarized" as const,
    participants: [
      { name: "James Whitaker", role: "Lead Attorney", color: "#2563EB" },
      { name: "Sarah Kimball", role: "Associate", color: "#059669" },
      { name: "Detective Ryan Kimura", role: "Lead Detective, Provo PD", color: "#7C3AED" },
      { name: "Victoria Mercer", role: "Client", color: "#DC2626" },
    ],
    summary: "Initial strategy meeting following reclassification of Nathan Mercer's death from accident to undetermined. Reviewed preliminary police reports, discussed evidence preservation, outlined investigation priorities, and addressed Victoria Mercer's dual status as client and potential person of interest. Key revelation: Detective Kimura disclosed that scaffolding bolts appeared deliberately tampered with.",
    mainPoints: [
      "Medical examiner reclassified death as 'undetermined' based on inconsistent blunt force trauma patterns",
      "4 of 6 scaffolding bolts show tool marks consistent with deliberate loosening",
      "Victoria Mercer's alibi has a 45-minute gap during critical window",
      "Derek Rawlings' fingerprints found in construction trailer despite claiming 2-week absence",
      "Tyler Blackwood's phone GPS places him near site at 9:47 PM",
      "Need to subpoena Rawlings' financial records and phone records immediately",
    ],
    topics: [
      { title: "Scene Analysis and Forensic Evidence", content: "Detective Kimura walked through the scene findings. The scaffolding at Building 7 collapsed at approximately 9:30 PM based on noise complaints from nearby Canyon Road residents. Four of six load-bearing bolts were backed out approximately 3/4 turn using what appears to be a 15mm socket wrench. This is enough to pass a visual inspection but would fail under dynamic load when someone climbed the scaffolding. Nathan's body was found at the base with injuries consistent with a 35-foot fall, but the ME noted additional blunt force trauma to the occipital region that doesn't match the fall trajectory." },
      { title: "Victoria Mercer - Alibi and Insurance", content: "Victoria states she was at her neighbor Karen Whitfield's book club from 7:30-10 PM. However, Whitfield's statement indicates Victoria left around 9:15 PM 'to take a phone call in her car' and returned approximately 20 minutes later. This creates a gap during the critical 9:15-9:45 PM window. Additionally, Nathan had a $5M life insurance policy with double indemnity for accidental death, making the total potential payout $10M. Victoria was the sole beneficiary. She also consulted divorce attorney Randall Kemp on December 26." },
      { title: "Derek Rawlings - Financial Motive", content: "Preliminary review of Canyon Vista Development accounts shows suspicious transfers. The operating agreement includes a buy-sell provision: if one partner dies, the surviving partner has the right to acquire the deceased's share at book value rather than fair market value. This could be worth $3-4M difference to Rawlings. Combined with the embezzlement exposure and gambling debts, Rawlings had the strongest financial motive. His fingerprints in the trailer are unexplained." },
      { title: "Tyler Blackwood - Estranged Son", content: "Tyler returned to Provo in November after 6 years away. He demanded $500K from Nathan on December 15, which was denied. Phone records show 14 calls to Derek Rawlings in the week before Nathan's death. His phone GPS places him within 0.3 miles of Canyon Vista at 9:47 PM. However, he was on a verified 22-minute call with his ex-girlfriend in Portland from 10:05-10:27 PM, and no physical evidence ties him to the scaffolding." },
    ],
    transcript: [
      { text: "Thank you all for coming. The situation has changed significantly since the initial accident classification.", speaker: "James Whitaker", timestamp: "00:00" },
      { text: "I need to inform you that our forensic team has determined the scaffolding failure was not accidental. Four bolts were deliberately loosened.", speaker: "Detective Ryan Kimura", timestamp: "02:15" },
      { text: "Oh my God. You are saying someone killed Nathan?", speaker: "Victoria Mercer", timestamp: "03:00" },
      { text: "We are treating this as a suspicious death. Mrs. Mercer, I need to ask about your whereabouts that evening.", speaker: "Detective Ryan Kimura", timestamp: "03:30" },
      { text: "I was at Karen Whitfield's book club. I already told the officers.", speaker: "Victoria Mercer", timestamp: "04:00" },
      { text: "We should note that Mrs. Whitfield's statement indicates you left the book club around 9:15 to take a phone call.", speaker: "Sarah Kimball", timestamp: "05:15" },
      { text: "I stepped out to my car for maybe 15 or 20 minutes. I had to take a call from my sister in California.", speaker: "Victoria Mercer", timestamp: "05:45" },
      { text: "We will need to verify that call. Moving on - Detective, what can you tell us about the other persons of interest?", speaker: "James Whitaker", timestamp: "06:30" },
      { text: "Derek Rawlings is a significant concern. His fingerprints were found in the construction trailer even though he told us he had not been to the site in two weeks.", speaker: "Detective Ryan Kimura", timestamp: "07:00" },
      { text: "And there is Tyler Blackwood, Nathan's son from his first marriage. His phone was near the site that night.", speaker: "Sarah Kimball", timestamp: "10:45" },
    ],
    actionItems: [
      { id: "ai-1", text: "Subpoena Derek Rawlings' bank records from Zions Bank and Chase", dueDate: "2026-01-18", assignee: "Sarah Kimball", completed: true },
      { id: "ai-2", text: "Obtain Victoria Mercer's phone records to verify 9:15 PM call", dueDate: "2026-01-15", assignee: "Sarah Kimball", completed: true },
      { id: "ai-3", text: "Request full forensic analysis of scaffolding bolts from Utah DPS Crime Lab", dueDate: "2026-01-20", assignee: "James Whitaker", completed: true },
      { id: "ai-4", text: "Interview Karen Whitfield regarding Victoria's alibi gap", dueDate: "2026-01-16", assignee: "Sarah Kimball", completed: true },
      { id: "ai-5", text: "File motion to preserve Canyon Vista security camera footage", dueDate: "2026-01-14", assignee: "James Whitaker", completed: true },
      { id: "ai-6", text: "Research buy-sell provision in Canyon Vista operating agreement", dueDate: "2026-01-19", assignee: "Sarah Kimball", completed: false },
    ],
    tags: ["Criminal", "Investigation", "Strategy"],
    createdBy: "james-whitaker",
  },
  {
    title: "Rawlings Financial Investigation - Forensic Accounting Review",
    date: "2026-01-24T14:00:00.000Z",
    duration: 55,
    status: "summarized" as const,
    participants: [
      { name: "James Whitaker", role: "Lead Attorney", color: "#2563EB" },
      { name: "Sandra Petrov", role: "CPA, Eide Bailly LLP", color: "#059669" },
      { name: "Sarah Kimball", role: "Associate", color: "#7C3AED" },
    ],
    summary: "Deep dive into the forensic accounting findings from Eide Bailly's investigation of Canyon Vista Development LLC financials. Sandra Petrov presented detailed findings showing $1.2M in unauthorized transfers by Derek Rawlings, including gambling debts, shell companies, and potential money laundering. Critical new finding: Rawlings had applied for a $500K personal line of credit two days before Nathan's death, suggesting acute financial desperation.",
    mainPoints: [
      "47 unauthorized transfers totaling $1,247,832 traced to Rawlings over 18 months",
      "$890,000 paid to 'Desert Sun Enterprises' - traced to unlicensed gambling operation in West Valley City",
      "Two Cayman Islands accounts discovered with $340,000 combined balance",
      "Rawlings applied for $500K credit line on January 6, 2026 - denied due to debt-to-income ratio",
      "Buy-sell agreement values Nathan's share at $2.1M book value vs. estimated $5.8M fair market value",
      "Pattern suggests escalating desperation in final weeks before Nathan's death",
    ],
    topics: [
      { title: "Transfer Pattern Analysis", content: "Sandra Petrov presented a detailed timeline of 47 unauthorized transfers from Canyon Vista operating account. Initial transfers were small ($5,000-$15,000) and disguised as vendor payments to fictitious companies. By late 2025, transfers became larger and more frequent - $75,000 in November, $120,000 in December. The pattern suggests Rawlings was either facing increasing pressure from creditors or becoming more brazen as he gained confidence the theft wouldn't be detected." },
      { title: "Gambling Connection", content: "$890,000 in payments were traced to 'Desert Sun Enterprises,' which the FBI has identified as a front for an unlicensed gambling operation in West Valley City run by Konstantin Petrov (no relation to our forensic accountant). This operation is under separate federal investigation. Rawlings' exposure to this operation creates additional motive - if he couldn't pay, he may have faced threats from the operators." },
      { title: "Buy-Sell Agreement Windfall", content: "The Canyon Vista Development LLC operating agreement includes a buy-sell provision triggered by partner death. The surviving partner can acquire the deceased's 50% share at book value. Nathan's share has a book value of $2.1M but estimated fair market value of $5.8M given project completion trajectory. This means Rawlings stands to gain a $3.7M windfall by acquiring Nathan's share at the discounted book value." },
    ],
    transcript: [
      { text: "Sandra, please walk us through the key findings from the forensic accounting review.", speaker: "James Whitaker", timestamp: "00:00" },
      { text: "We identified 47 unauthorized transfers over 18 months totaling $1,247,832. The money went to personal accounts, shell companies, and a gambling operation.", speaker: "Sandra Petrov", timestamp: "01:00" },
      { text: "Can you explain the gambling connection?", speaker: "Sarah Kimball", timestamp: "05:30" },
      { text: "Desert Sun Enterprises is a front for an illegal gambling operation. Rawlings has been paying them regularly, which suggests significant gambling losses.", speaker: "Sandra Petrov", timestamp: "06:00" },
      { text: "What about the buy-sell provision? How much does Rawlings stand to gain?", speaker: "James Whitaker", timestamp: "12:00" },
      { text: "If he acquires Nathan's share at book value, the difference is approximately $3.7 million. That is an enormous financial incentive.", speaker: "Sandra Petrov", timestamp: "12:30" },
    ],
    actionItems: [
      { id: "ai-7", text: "Prepare forensic accounting summary for prosecution team", dueDate: "2026-01-30", assignee: "Sandra Petrov", completed: true },
      { id: "ai-8", text: "File emergency TRO to freeze Rawlings' assets", dueDate: "2026-01-28", assignee: "James Whitaker", completed: true },
      { id: "ai-9", text: "Subpoena Cayman Islands account records through MLAT treaty", dueDate: "2026-02-15", assignee: "Sarah Kimball", completed: false },
      { id: "ai-10", text: "Contact FBI regarding Desert Sun Enterprises gambling investigation", dueDate: "2026-02-01", assignee: "James Whitaker", completed: false },
    ],
    tags: ["Financial", "Forensic Accounting", "Fraud"],
    createdBy: "james-whitaker",
  },
  {
    title: "The Nathan Mercer Twist - Emergency Team Briefing",
    date: "2026-02-03T16:00:00.000Z",
    duration: 42,
    status: "summarized" as const,
    participants: [
      { name: "James Whitaker", role: "Lead Attorney", color: "#2563EB" },
      { name: "Sarah Kimball", role: "Associate", color: "#059669" },
      { name: "Detective Ryan Kimura", role: "Lead Detective, Provo PD", color: "#7C3AED" },
    ],
    summary: "Emergency briefing following digital forensics recovery of deleted data from Nathan Mercer's phone. Bombshell revelation: Nathan Mercer was planning to fake his own death to collect insurance money and flee to Belize. This changes the entire case theory. Did someone discover Nathan's plan and use it against him? Was the scaffolding tampered with by someone who knew Nathan would be at the site that night? The investigation has shifted from 'who wanted Nathan dead' to 'who knew Nathan's plan and turned it against him.'",
    mainPoints: [
      "Nathan's deleted searches: 'fake death insurance fraud,' 'countries without US extradition'",
      "Draft email to offshore attorney in Belize discussing 'new identity documents'",
      "Text messages to unknown burner number about '$2M cash position' and 'Cayman account ready'",
      "Nathan may have intended to stage the scaffolding accident himself",
      "Someone may have discovered the plan and ensured the 'accident' was real",
      "This potentially exonerates Victoria if she was part of the scheme (motive changes)",
      "New theory: Did Rawlings discover the plan and accelerate it for the buy-sell windfall?",
    ],
    topics: [
      { title: "The Fake Death Plan", content: "Digital forensics recovered deleted searches from Nathan's iPhone dating January 3-5, 2026. He searched for 'how to fake your own death insurance,' 'countries without US extradition treaty,' 'Belize residency requirements,' and 'offshore banking privacy.' A draft email to a Belize-based attorney named Carlos Mendoza discussed 'new identity documents' and 'property purchase under alternative name.' Text messages to an unidentified burner number referenced '$2M cash position' and 'Cayman account ready for transfer.'" },
      { title: "Revised Case Theory", content: "This discovery fundamentally changes our investigation. Nathan may have planned to loosen the scaffolding bolts himself, stage a fall while actually escaping, and have someone discover the 'body' (possibly a collaborator who would plant evidence). But someone either discovered the plan or was involved in it and decided to make the fake death real. The 0.14 BAC and alprazolam in his system may have been part of his own staging (to explain disorientation) or administered by his killer." },
      { title: "Impact on Suspects", content: "Victoria: If she knew about the plan, her motive shifts from murder to potential conspiracy. The divorce attorney consultation may have been cover, not genuine intent to divorce. Rawlings: If he discovered Nathan's exit plan, he had even more motive - Nathan was about to disappear with company assets and leave Rawlings holding the bag for the embezzlement and OSHA violations. Tyler: Phone calls with Rawlings take on new meaning - was Rawlings recruiting Tyler to help with the real murder while Tyler thought they were just getting even with Nathan?" },
    ],
    transcript: [
      { text: "We need to discuss something that changes everything about this case.", speaker: "Detective Ryan Kimura", timestamp: "00:00" },
      { text: "Digital forensics has recovered deleted data from Nathan Mercer's phone. He was planning to fake his own death.", speaker: "Detective Ryan Kimura", timestamp: "00:30" },
      { text: "You are telling me the victim was planning to stage his own death?", speaker: "James Whitaker", timestamp: "01:15" },
      { text: "Yes. He searched for fake death schemes, had an email draft to a Belize attorney about new identity documents, and texts about millions in offshore accounts.", speaker: "Detective Ryan Kimura", timestamp: "01:45" },
      { text: "This means someone may have discovered his plan and decided to make the fake death real.", speaker: "Sarah Kimball", timestamp: "03:00" },
      { text: "Exactly. And the question becomes - who knew about Nathan's plan? His wife? His partner? His son?", speaker: "Detective Ryan Kimura", timestamp: "03:30" },
      { text: "If Rawlings found out Nathan was about to disappear with company money, that gives him even more motive to act first.", speaker: "James Whitaker", timestamp: "05:00" },
    ],
    actionItems: [
      { id: "ai-11", text: "Trace the burner phone number from Nathan's deleted texts", dueDate: "2026-02-10", assignee: "Detective Ryan Kimura", completed: false },
      { id: "ai-12", text: "Contact Carlos Mendoza in Belize for information about Nathan's communications", dueDate: "2026-02-15", assignee: "Sarah Kimball", completed: false },
      { id: "ai-13", text: "Re-interview Victoria about knowledge of offshore accounts", dueDate: "2026-02-08", assignee: "James Whitaker", completed: false },
      { id: "ai-14", text: "Check if Rawlings accessed Nathan's phone or computer before death", dueDate: "2026-02-07", assignee: "Detective Ryan Kimura", completed: false },
      { id: "ai-15", text: "Revised case theory memo for prosecution team", dueDate: "2026-02-12", assignee: "Sarah Kimball", completed: false },
    ],
    tags: ["Critical Development", "Investigation", "Case Theory"],
    createdBy: "james-whitaker",
  },
];

const demoTasks = [
  { groupName: "Critical - Immediate", title: "Trace burner phone from Nathan's deleted texts", description: "Digital forensics recovered texts to unidentified burner number discussing '$2M cash position' and 'Cayman account ready.' Need carrier records and IMEI trace to identify the other party in Nathan's escape plan.", status: "working-on-it" as const, priority: "critical" as const, progress: 35, tags: ["investigation", "digital-forensics", "critical"], notes: "Subpoena sent to T-Mobile Jan 30. Awaiting response." },
  { groupName: "Critical - Immediate", title: "Re-interview Victoria Mercer re: offshore accounts", description: "Following discovery of Nathan's fake death plan, need to determine if Victoria knew about offshore accounts and escape scheme. Her knowledge changes her status from suspect to potential co-conspirator or innocent party.", status: "not-started" as const, priority: "critical" as const, progress: 0, tags: ["interview", "client", "critical"], notes: "Schedule through her attorney. She may invoke spousal privilege." },
  { groupName: "Critical - Immediate", title: "File opposition to Fidelity's motion to dismiss insurance claim", description: "Fidelity National filed MTD arguing exclusion clauses. Must argue death was not during commission of crime and not suicide. Due February 15.", status: "working-on-it" as const, priority: "critical" as const, progress: 55, tags: ["insurance", "deadline", "motion"], notes: "Draft in progress. Key argument: even if Nathan planned fraud, his actual death was homicide by third party." },
  { groupName: "Active Investigation", title: "Analyze unidentified fingerprint on scaffolding bolt #3", description: "Partial fingerprint on tampered bolt does not match any known suspect. Submitted to AFIS with no return. Need to expand search to construction workers, subcontractors, and any other persons with site access.", status: "working-on-it" as const, priority: "high" as const, progress: 40, tags: ["forensics", "fingerprint", "mystery"], notes: "Requesting prints from all 23 subcontractor employees who worked on Building 7." },
  { groupName: "Active Investigation", title: "Identify dark SUV from security camera footage", description: "Unidentified dark SUV entered Canyon Vista at 8:45 PM, departed 9:38 PM on night of death. Plates obscured by mud. Preliminary analysis suggests 2022-2024 Chevrolet Tahoe. Derek Rawlings drives a 2023 black Tahoe.", status: "working-on-it" as const, priority: "high" as const, progress: 60, tags: ["evidence", "vehicle", "surveillance"], notes: "FBI image enhancement lab working on plate recovery. Also checking tire track impressions from site entrance." },
  { groupName: "Active Investigation", title: "Interview Rachel Rawlings about Derek's alibi", description: "Derek claims he was home with wife Rachel on night of death. Rachel has not been interviewed independently. She is Derek's alibi witness AND Officer Hensley's sister. Complex family dynamics may affect testimony.", status: "not-started" as const, priority: "high" as const, progress: 0, tags: ["alibi", "interview", "rawlings"], notes: "Her attorney says she'll cooperate but wants immunity deal first." },
  { groupName: "Active Investigation", title: "OSHA violation response - Canyon Vista", description: "Prepare response to Utah OSHA preliminary findings citing willful violations. Potential penalties of $156K+ per violation. Need to separate company liability from individual partner liability given Rawlings' embezzlement.", status: "working-on-it" as const, priority: "medium" as const, progress: 25, tags: ["regulatory", "OSHA", "compliance"], notes: "Working with safety consultant to prepare remediation plan." },
  { groupName: "Discovery & Motions", title: "Subpoena Cayman Islands account records", description: "File MLAT (Mutual Legal Assistance Treaty) request through DOJ to obtain records from two Cayman Islands accounts linked to Derek Rawlings. Process takes 60-90 days minimum.", status: "working-on-it" as const, priority: "medium" as const, progress: 20, tags: ["subpoena", "international", "financial"], notes: "DOJ liaison contacted. They need formal letter rogatory." },
  { groupName: "Discovery & Motions", title: "Prepare Rawlings deposition outline", description: "Derek Rawlings deposition scheduled for February 20. Must cover: January 8 whereabouts, construction trailer access, relationship with Tyler Blackwood, knowledge of Nathan's plans, financial transfers, gambling debts, and buy-sell agreement.", status: "working-on-it" as const, priority: "high" as const, progress: 70, tags: ["deposition", "rawlings", "discovery"], notes: "Focus on timeline inconsistencies and fingerprint explanation." },
  { groupName: "Discovery & Motions", title: "Motion to compel Officer Hensley's personal phone records", description: "Need to determine if Hensley communicated with Rawlings before or during response to Canyon Vista. He claims body cam gap was weather-related but digital forensics is inconclusive. Personal phone records may show coordination.", status: "not-started" as const, priority: "medium" as const, progress: 0, tags: ["motion", "hensley", "phone-records"], notes: "Will face police union opposition. Need strong probable cause showing." },
  { groupName: "Discovery & Motions", title: "Draft motion to dismiss corruption charges - Mayor Foster", description: "Prepare MTD arguing campaign contributions were lawful and text messages don't establish quid pro quo. Challenge prosecution's interpretation of Utah Code 76-8-105.", status: "working-on-it" as const, priority: "medium" as const, progress: 30, tags: ["motion", "corruption", "foster"], notes: "Researching comparable Utah corruption cases for precedent." },
  { groupName: "Research & Analysis", title: "Research Utah scaffolding safety standards", description: "Compile relevant OSHA regulations (29 CFR 1926 Subpart L) and Utah-specific construction safety requirements for scaffolding. Need to establish standard of care for negligence claims.", status: "done" as const, priority: "medium" as const, progress: 100, tags: ["research", "OSHA", "scaffolding"], notes: "Complete. Key finding: Utah adopts federal OSHA standards with additional state requirements for fall protection." },
  { groupName: "Research & Analysis", title: "Prior art research - Utah wrongful death statutes", description: "Research Utah Code 78B-3-106 (wrongful death) and applicable case law for potential civil wrongful death suit. Review statute of limitations, damage caps, and comparative fault rules.", status: "working-on-it" as const, priority: "low" as const, progress: 45, tags: ["research", "wrongful-death", "utah-law"], notes: "Key case: Daniels v. Riverton City (2020) - comparative fault in construction death." },
  { groupName: "Completed", title: "File emergency TRO to freeze Rawlings' assets", description: "Emergency motion filed and granted January 30. Rawlings' personal accounts, Rawlings Holdings LLC, and Mountain Peak Ventures accounts frozen pending resolution.", status: "done" as const, priority: "critical" as const, progress: 100, tags: ["TRO", "completed", "asset-freeze"], notes: "Order signed by Judge Worthington. Rawlings objected but hearing set for Feb 14." },
  { groupName: "Completed", title: "Obtain and preserve all security camera footage", description: "Secured all 6 security camera feeds from Canyon Vista Estates for January 8, 2026. Footage preserved with chain of custody documentation.", status: "done" as const, priority: "high" as const, progress: 100, tags: ["evidence", "preservation", "completed"], notes: "All footage secured and hash-verified. Copies stored with Utah DPS." },
  { groupName: "Completed", title: "Initial client intake - Victoria Mercer", description: "Completed intake with Victoria Mercer as estate representative. Retainer agreement signed. Conflict check completed - no conflicts identified with firm's other clients.", status: "done" as const, priority: "medium" as const, progress: 100, tags: ["intake", "completed"], notes: "Retainer: $50,000 initial deposit against $450/hr." },
];

const demoTimeEntries = [
  { matterIndex: 0, userId: "james-whitaker", userName: "James Whitaker", date: "2026-01-10", hours: 2.5, description: "Initial case review and police report analysis. Reviewed incident report, identified key witnesses, outlined investigation strategy.", billableStatus: "billable", hourlyRate: 450, activityCode: "L100" },
  { matterIndex: 0, userId: "sarah-kimball", userName: "Sarah Kimball", date: "2026-01-12", hours: 3.0, description: "Attended strategy meeting with Det. Kimura and Victoria Mercer. Prepared follow-up memorandum summarizing key findings and action items.", billableStatus: "billable", hourlyRate: 350, activityCode: "A101" },
  { matterIndex: 0, userId: "james-whitaker", userName: "James Whitaker", date: "2026-01-15", hours: 4.5, description: "Drafted and filed emergency motion to preserve Canyon Vista security camera footage. Researched spoliation doctrine under Utah law.", billableStatus: "billable", hourlyRate: 450, activityCode: "L110" },
  { matterIndex: 0, userId: "sarah-kimball", userName: "Sarah Kimball", date: "2026-01-18", hours: 5.0, description: "Reviewed Rawlings phone and bank records received via subpoena. Identified 47 suspicious transfers. Prepared summary chart for team review.", billableStatus: "billable", hourlyRate: 350, activityCode: "L120" },
  { matterIndex: 0, userId: "james-whitaker", userName: "James Whitaker", date: "2026-01-22", hours: 2.0, description: "Reviewed supplemental medical examiner report. Analyzed toxicology findings (BAC 0.14, alprazolam). Consulted with toxicology expert.", billableStatus: "billable", hourlyRate: 450, activityCode: "L100" },
  { matterIndex: 0, userId: "sarah-kimball", userName: "Sarah Kimball", date: "2026-01-24", hours: 3.5, description: "Attended forensic accounting review meeting with Sandra Petrov, Eide Bailly. Prepared detailed notes on Rawlings embezzlement findings.", billableStatus: "billable", hourlyRate: 350, activityCode: "A101" },
  { matterIndex: 1, userId: "james-whitaker", userName: "James Whitaker", date: "2026-01-28", hours: 6.0, description: "Drafted complaint for insurance bad faith and breach of contract against Fidelity National. Researched double indemnity provisions and contestability clauses.", billableStatus: "billable", hourlyRate: 450, activityCode: "L110" },
  { matterIndex: 3, userId: "james-whitaker", userName: "James Whitaker", date: "2026-01-28", hours: 3.0, description: "Drafted emergency TRO motion to freeze Rawlings' personal and shell company assets. Filed same day - hearing set for Jan 30.", billableStatus: "billable", hourlyRate: 450, activityCode: "L110" },
  { matterIndex: 3, userId: "james-whitaker", userName: "James Whitaker", date: "2026-01-30", hours: 4.0, description: "Attended TRO hearing before Judge Worthington. Presented forensic accounting evidence. Order granted freezing Rawlings' assets.", billableStatus: "billable", hourlyRate: 450, activityCode: "A106" },
  { matterIndex: 0, userId: "sarah-kimball", userName: "Sarah Kimball", date: "2026-02-03", hours: 2.5, description: "Attended emergency briefing re: Nathan Mercer's deleted phone data. Reviewed fake death scheme evidence. Began drafting revised case theory memo.", billableStatus: "billable", hourlyRate: 350, activityCode: "A101" },
  { matterIndex: 4, userId: "james-whitaker", userName: "James Whitaker", date: "2026-02-01", hours: 1.5, description: "Initial consultation with Mayor Foster regarding public integrity investigation. Reviewed campaign finance records and text message evidence.", billableStatus: "billable", hourlyRate: 450, activityCode: "A101" },
  { matterIndex: 5, userId: "sarah-kimball", userName: "Sarah Kimball", date: "2026-01-20", hours: 3.0, description: "Reviewed Tyler Blackwood GPS data analysis. Prepared timeline chart showing Blackwood's movements on January 8. Analyzed phone records showing calls to Rawlings.", billableStatus: "billable", hourlyRate: 350, activityCode: "L120" },
];

const demoCalendarEvents = [
  { matterIndex: 0, title: "Rawlings Deposition", eventType: "deposition", startDate: "2026-02-20T09:00:00.000Z", endDate: "2026-02-20T16:00:00.000Z", allDay: false, location: "Fourth District Court, Provo, UT", attendees: ["James Whitaker", "Sarah Kimball", "Derek Rawlings", "Steven Waterman (opposing)"], reminderMinutes: 1440, color: "#ef4444", createdBy: "james-whitaker" },
  { matterIndex: 0, title: "Scaffolding Expert Site Inspection", eventType: "inspection", startDate: "2026-02-12T10:00:00.000Z", endDate: "2026-02-12T14:00:00.000Z", allDay: false, location: "Canyon Vista Estates, Provo Canyon, UT", attendees: ["Dr. Alan Richter, P.E.", "Sarah Kimball", "CSI Unit"], reminderMinutes: 1440, color: "#3b82f6", createdBy: "james-whitaker" },
  { matterIndex: 1, title: "Insurance Bad Faith - Initial Case Management Conference", eventType: "hearing", startDate: "2026-02-25T14:00:00.000Z", endDate: "2026-02-25T15:00:00.000Z", allDay: false, location: "Fourth District Court, Judge Durham's chambers", attendees: ["James Whitaker", "James Holbrook (Snell & Wilmer)"], reminderMinutes: 1440, color: "#7c3aed", createdBy: "james-whitaker" },
  { matterIndex: 3, title: "TRO Continuation Hearing - Asset Freeze", eventType: "hearing", startDate: "2026-02-14T09:00:00.000Z", endDate: "2026-02-14T11:00:00.000Z", allDay: false, location: "Fourth District Court, Judge Worthington", attendees: ["James Whitaker", "Steven Waterman (opposing)", "Derek Rawlings"], reminderMinutes: 1440, color: "#dc2626", createdBy: "james-whitaker" },
  { matterIndex: 0, title: "Victoria Mercer Re-Interview (Offshore Accounts)", eventType: "meeting", startDate: "2026-02-08T10:00:00.000Z", endDate: "2026-02-08T12:00:00.000Z", allDay: false, location: "Law Office, 200 East Center Street, Provo", attendees: ["James Whitaker", "Victoria Mercer", "Sarah Kimball"], reminderMinutes: 1440, color: "#f59e0b", createdBy: "james-whitaker" },
  { matterIndex: 5, title: "Tyler Blackwood - Status Conference", eventType: "hearing", startDate: "2026-02-18T10:00:00.000Z", endDate: "2026-02-18T11:00:00.000Z", allDay: false, location: "Fourth District Court, Judge Worthington", attendees: ["Sarah Kimball", "ADA Patricia Nguyen"], reminderMinutes: 1440, color: "#7c3aed", createdBy: "sarah-kimball" },
  { matterIndex: 0, title: "Deadline: Opposition to Fidelity MTD", eventType: "deadline", startDate: "2026-02-15T23:59:00.000Z", allDay: true, location: "eFiling - Fourth District Court", attendees: ["James Whitaker"], reminderMinutes: 4320, color: "#ef4444", createdBy: "james-whitaker" },
  { matterIndex: 4, title: "Grand Jury Appearance - Mayor Foster", eventType: "hearing", startDate: "2026-03-05T09:00:00.000Z", endDate: "2026-03-05T12:00:00.000Z", allDay: false, location: "Utah County Courthouse, Grand Jury Room", attendees: ["James Whitaker", "Linda Foster"], reminderMinutes: 2880, color: "#ec4899", createdBy: "james-whitaker" },
];

export async function seedDemoData() {
  console.log("Starting Mercer Case demo data seeding...");

  try {
    const createdClients: any[] = [];
    for (const client of demoClients) {
      const created = await storage.createClient(client);
      createdClients.push(created);
      console.log(`Created client: ${client.name}`);
    }

    const createdMatters: any[] = [];
    for (const matter of demoMatters) {
      const clientId = createdClients[matter.clientIndex].id;
      const { clientIndex, ...matterData } = matter;
      const created = await storage.createMatter({ ...matterData, clientId });
      createdMatters.push(created);
      console.log(`Created matter: ${matter.name}`);
    }

    for (const file of demoFiles) {
      const matterId = createdMatters[file.matterIndex].id;
      const { matterIndex, profile, ...fileData } = file;
      const createdFile = await storage.createFileItem({ ...fileData, matterId });
      if (profile) {
        await storage.createDocProfile({ ...profile, fileId: createdFile.id });
      }
      console.log(`Created file: ${file.fileName}`);
    }

    for (const evidence of demoEvidence) {
      const matterId = createdMatters[evidence.matterIndex].id;
      const { matterIndex, ...evidenceData } = evidence;
      await storage.createEvidenceVaultFile({ ...evidenceData, matterId });
      console.log(`Created evidence: ${evidence.originalName}`);
    }

    for (const nodeData of demoDetectiveNodes) {
      const matterId = createdMatters[nodeData.matterIndex].id;
      const createdNodes: any[] = [];
      for (const node of nodeData.nodes) {
        const created = await storage.createDetectiveNode({ ...node, matterId });
        createdNodes.push(created);
      }
      for (const conn of nodeData.connections) {
        await storage.createDetectiveConnection({
          matterId,
          sourceNodeId: createdNodes[conn.sourceIndex].id,
          targetNodeId: createdNodes[conn.targetIndex].id,
          label: conn.label,
          connectionType: conn.connectionType,
          strength: 3,
          notes: "",
        });
      }
      console.log(`Created detective board with ${nodeData.nodes.length} nodes and ${nodeData.connections.length} connections`);
    }

    for (const meeting of demoMeetings) {
      await storage.createMeeting(meeting);
      console.log(`Created meeting: ${meeting.title}`);
    }

    for (const entry of demoTimeEntries) {
      const matterId = createdMatters[entry.matterIndex].id;
      const { matterIndex, ...entryData } = entry;
      await storage.createTimeEntry({ ...entryData, matterId });
      console.log(`Created time entry: ${entry.description.substring(0, 50)}...`);
    }

    for (const event of demoCalendarEvents) {
      const matterId = createdMatters[event.matterIndex].id;
      const { matterIndex, ...eventData } = event;
      await storage.createCalendarEvent({ ...eventData, matterId });
      console.log(`Created calendar event: ${event.title}`);
    }

    const boards = await storage.getBoards();
    if (boards.length > 0) {
      const boardId = boards[0].id;
      const groups = await storage.getGroups(boardId);
      
      for (const task of demoTasks) {
        const group = groups.find(g => g.title === task.groupName) || groups[0];
        const { groupName, ...taskData } = task;
        await storage.createTask({
          ...taskData,
          boardId,
          groupId: group.id,
          assignees: [],
          owner: null,
          timeEstimate: null,
          customFields: {},
          subtasks: [],
        });
        console.log(`Created task: ${task.title}`);
      }
    }

    console.log("\n=== Mercer Case Demo Data Seeding Complete ===");
    console.log(`Created: ${createdClients.length} clients, ${createdMatters.length} matters`);
    console.log(`Created: ${demoFiles.length} files, ${demoEvidence.length} evidence items`);
    console.log(`Created: ${demoMeetings.length} meetings, ${demoTimeEntries.length} time entries`);
    console.log(`Created: ${demoCalendarEvents.length} calendar events`);
    console.log(`Created: ${demoDetectiveNodes[0].nodes.length} detective nodes, ${demoDetectiveNodes[0].connections.length} connections`);
    
  } catch (error) {
    console.error("Error seeding Mercer Case demo data:", error);
    throw error;
  }
}
